In [1]:
!pip install beutifulsoup4
!pip install requests

NameError: name 'html_doc' is not defined

In [2]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
soup = requests.get(url)
soup = BeautifulSoup(soup.text, "lxml")
soup

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]--><!--[if IE 9]> <html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID - Coronavirus Statistics - Worldometer</title>
<meta content="Daily and weekly updated statistics tracking the number of COVID-19 cases, recovered, and deaths. Historical data with cumulative charts, graphs, and updates." name="description"/>
<!-- Favicon -->
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- og image -->
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>
<!-- Bootstrap -->
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<!-- font awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<script src="/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<!-- tables
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js"></script>
 -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<!-- FREESTAR -->
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</head>
<body>
<!-- Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<!--
<script type="text/javascript" async=true>
(function() {
  var host = 'worldometers.info';
  var element = document.createElement('script');
  var firstScript = document.getElementsByTagName('script')[0];
  var url = 'https://quantcast.mgr.consensu.org'
    .concat('/choice/', 'Pd9JxUkvV0m7q', '/', host, '/choice.js');
  var uspTries = 0;
  var uspTriesLimit = 3;
  element.async = true;
  element.type = 'text/javascript';
  element.src = url;

  firstScript.parentNode.insertBefore(element, firstScript);

  function makeStub() {
    var TCF_LOCATOR_NAME = '__tcfapiLocator';
    var queue = [];
    var win = window;
    var cmpFrame;

    function addFrame() {
      var doc = win.document;
      var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

      if (!otherCMP) {
        if (doc.body) {
          var iframe = doc.createElement('iframe');

          iframe.style.cssText = 'display:none';
          iframe.name = TCF_LOCATOR_NAME;
          doc.body.appendChild(iframe);
        } else {
          setTimeout(addFrame, 5);
        }
      }
      return !otherCMP;
    }

    function tcfAPIHandler() {
      var gdprApplies;
      var args = arguments;

      if (!args.length) {
        return queue;
      } else if (args[0] === 'setGdprApplies') {
        if (
          args.length > 3 &&
          args[2] === 2 &&
          typeof args[3] === 'boolean'
        ) {
          gdprApplies = args[3];
          if (typeof args[2] === 'function') {
            args[2]('set', true);
          }
        }
      } else if (args[0] === 'ping') {
        var retr = {
          gdprApplies: gdprApplies,
          cmpLoaded: false,
          cmpStatus: 'stub'
        };

        if (typeof args[2] === 'function') {
          args[2](retr);
        }
      } else {
        queue.push(args);
      }
    }

    function postMessageEventHandler(event) {
      var msgIsString = typeof event.data === 'string';
      var json = {};

      try {
        if (msgIsString) {
          json = JSON.parse(event.data);
        } else {
          json = event.data;
        }
      } catch (ignore) {}

      var payload = json.__tcfapiCall;

      if (payload) {
        window.__tcfapi(
          payload.command,
          payload.version,
          function(retValue, success) {
            var returnMsg = {
              __tcfapiReturn: {
                returnValue: retValue,
                success: success,
                callId: payload.callId
              }
            };
            if (msgIsString) {
              returnMsg = JSON.stringify(returnMsg);
            }
            event.source.postMessage(returnMsg, '*');
          },
          payload.parameter
        );
      }
    }

    while (win) {
      try {
        if (win.frames[TCF_LOCATOR_NAME]) {
          cmpFrame = win;
          break;
        }
      } catch (ignore) {}

      if (win === window.top) {
        break;
      }
      win = win.parent;
    }
    if (!cmpFrame) {
      addFrame();
      win.__tcfapi = tcfAPIHandler;
      win.addEventListener('message', postMessageEventHandler, false);
    }
  };

  makeStub();

  var uspStubFunction = function() {
    var arg = arguments;
    if (typeof window.__uspapi !== uspStubFunction) {
      setTimeout(function() {
        if (typeof window.__uspapi !== 'undefined') {
          window.__uspapi.apply(window.__uspapi, arg);
        }
      }, 500);
    }
  };

  var checkIfUspIsReady = function() {
    uspTries++;
    if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
      console.warn('USP is not accessible');
    } else {
      clearInterval(uspInterval);
    }
  };

  if (typeof window.__uspapi === 'undefined') {
    window.__uspapi = uspStubFunction;
    var uspInterval = setInterval(checkIfUspIsReady, 6000);
  }
})();
</script>
-->
<!-- End Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<!-- GA wm old (info) -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<!-- GDPR consent -->
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/">Coronavirus</a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<!-- MAIN -->
<div class="container">
<!-- TOP AD -->
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- wm_top970 -->
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<!-- TOP AD -->
<!-- MAIN  -->
<!-- CENTER -->
<div class="row"> <div class="col-md-8">
<!-- *** CONTENT A *** -->
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<!-- charts -->
<script src="/js/highcharts.js"></script>
<style type="text/css">
    .source {}

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }

    .source111 {}

    .source1111 {
        font-size: 12px;
        color: #bbb;
    }


    .new_badge {

        position: absolute;
        font-size: 12px;
        top: -5px;
        right: -26px;
        background-color: #8ACA2B;
        color: white;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }

    .new_badge_link {

        background-color: #8ACA2B;
        color: white !important;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: June 02, 2023, 01:30 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a class="new_badge_link" href="/coronavirus/weekly-trends/" style="display: inline-block; position:relative;">Weekly Trends</a> - <a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">689,728,377        </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,885,457</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>662,070,197</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<!-- START -->
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }

    .collapse_button {

        position: absolute;
        right: 10px;
        pointer-events: none;
        color: #70757a !important;
        height: 24px;
        width: 24px;
        line-height: 24px;
    }

    .collapse_button svg {
        display: block;
        height: 100%;
        width: 100%;
        fill: currentColor;
    }

    .rotate_180 {

        transform: rotate(180deg);
    }

    .panel_clickable {

        cursor: pointer;
    }
</style>
<script>
    var do_not_slide = false;
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });


        $('.collapse').on('show.bs.collapse', function(el) {


            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.addClass('rotate_180');

            if (do_not_slide) {

                return;
            }

            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('show');
            } else {

                $('#panel_active').collapse('show');
            }

            do_not_slide = false;
        });

        $('.collapse').on('hide.bs.collapse', function(el) {

            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.removeClass('rotate_180');


            if (do_not_slide) {

                return;
            }


            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('hide');
            } else {

                $('#panel_active').collapse('hide');
            }

            do_not_slide = false;

        });



    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div aria-controls="panel_active" aria-expanded="false" class="panel_clickable panel-heading" data-toggle="collapse" href="#panel_active" style="text-align:center;position:relative;">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
                    Active Cases
                </span>
<span class="collapse_button"><svg focusable="false" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
</svg></span>
</div>
<div class="collapse" id="panel_active">
<div class="panel-body" style="text-align:center;min-height:220px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">20,772,723</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">20,734,699</span> (<strong>99.8</strong>%)

                                    <div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">38,024</span> (<strong>0.2</strong>%)
                                    <div style="font-size:13px">Serious or Critical</div><br/>
</div>
</div>
<a class="flip_cases_front" href="javascript: void(0);" style="clear: both;display: block;padding-top:20px;width:100%;">Show Graph</a>
</div>
<div class="panel_back" style="width:100%;height:100%;">
<div id="total-currently-infected-linear"></div>

In [3]:
table_code = soup.table
table_code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>126,752,183</td>
<td>+4,116</td>
<td>1,633,966</td>
<td>+29</td>
<td>122,650,408</td>
<td>+8,656</td>
<td>2,467,809</td>
<td>6,199</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>217,623,290</td>
<td>+28,413</td>
<td>1,546,687</td>
<td>+24</td>
<td>201,245,559</td>
<td>+19,969</td>
<td>14,831,044</td>
<td>15,334</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>249,411,422</td>
<td>+4,784</td>
<td>2,061,621</td>
<td>+17</td>
<td>245,413,020</td>
<td>+16,689</td>
<td>1,936,781</td>
<td>5,731</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>68,738,704</td>
<td>+1,494</td>
<td>1,356,298</td>
<td>+17</td>
<td>66,474,004</td>
<td>+830</td>
<td>908,402</td>
<td>10,113</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>14,378,181</td>
<td>+1</td>
<td>28,093</td>
<td></td>
<td>14,200,923</td>
<td>+1</td>
<td>149,165</td>
<td>99</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,823,876</td>
<td>+6</td>
<td>258,777</td>
<td></td>
<td>12,085,577</td>
<td>+3</td>
<td>479,522</td>
<td>548</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>689,728,377</td>
<td>+38,814</td>
<td>6,885,457</td>
<td>+87</td>
<td>662,070,197</td>
<td>+46,148</td>
<td>20,772,723</td>
<td>38,024</td>
<td>88,486</td>
<td>883.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">107,123,546</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,970</td>
<td style="font-weight: bold; text-align:right;">1,165,531                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+20</td>
<td style="font-weight: bold; text-align:right">105,213,261</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+7,455</td>
<td style="text-align:right;font-weight:bold;">744,754</td>
<td style="font-weight: bold; text-align:right">1,033</td>
<td style="font-weight: bold; text-align:right">319,958</td>
<td style="font-weight: bold; text-align:right">3,481</td>
<td style="font-weight: bold; text-align:right">1,180,371,249</td>
<td style="font-weight: bold; text-align:right">3,525,546</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>287</td><td>0</td>
<td style="font-weight: bold; text-align:right">9</td>
<td style="font-weight: bold; text-align:right">0.06</td>
<td style="font-weight: bold; text-align:right">2,224</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,990,876</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">531,872                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,455,079</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">3,925</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">31,985</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">930,414,363</td>
<td style="font-weight: bold; text-align:right">661,448</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,645</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">40,090,330</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,735</td>
<td style="font-weight: bold; text-align:right;">167,311                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,871,393</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+9,003</td>
<td style="text-align:right;font-weight:bold;">51,626</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">611,277</td>
<td style="font-weight: bold; text-align:right">2,551</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>392</td><td>0</td>
<td style="font-weight: bold; text-align:right">57</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">787</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,428,043</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">174,323                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,239,600</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">14,120</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">458,112</td>
<td style="font-weight: bold; text-align:right">2,078</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>481</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">168</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">37,601,257</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">702,907                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">649,189</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">174,602</td>
<td style="font-weight: bold; text-align:right">3,264</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>306</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,015</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,803,572</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">74,694                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">83</td>
<td style="font-weight: bold; text-align:right">269,169</td>
<td style="font-weight: bold; text-align:right">595</td>
<td style="font-weight: bold; text-align:right">100,414,883</td>
<td style="font-weight: bold; text-align:right">799,578</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,681</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">95,582</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">31,728,115</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+24,604</td>
<td style="font-weight: bold; text-align:right;">34,804                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+20</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">31,373,318</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+17,386</td>
<td style="text-align:right;font-weight:bold;">319,993</td>
<td style="font-weight: bold; text-align:right">166</td>
<td style="font-weight: bold; text-align:right">618,122</td>
<td style="font-weight: bold; text-align:right">678</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,475</td><td>3</td>
<td style="font-weight: bold; text-align:right">479</td>
<td style="font-weight: bold; text-align:right">0.4</td>
<td style="font-weight: bold; text-align:right">6,234</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,857,572</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">190,392                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">25,545,397</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">121,783</td>
<td style="font-weight: bold; text-align:right">75</td>
<td style="font-weight: bold; text-align:right">429,080</td>
<td style="font-weight: bold; text-align:right">3,159</td>
<td style="font-weight: bold; text-align:right">272,596,017</td>
<td style="font-weight: bold; text-align:right">4,523,456</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>317</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,021</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,603,076</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">225,324                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,370,933</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,597</td>
<td style="text-align:right;font-weight:bold;">6,819</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">359,180</td>
<td style="font-weight: bold; text-align:right">3,290</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>304</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">100</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">22,929,149</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">399,057                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">22,361,277</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">168,815</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">157,258</td>
<td style="font-weight: bold; text-align:right">2,737</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>365</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>

In [4]:
tags= table_code.find_all('tr')
tags

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>126,752,183</td>
 <td>+4,116</td>
 <td>1,633,966</td>
 <td>+29</td>
 <td>122,650,408</td>
 <td>+8,656</td>
 <td>2,467,809</td>
 <td>6,199</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>217,623,290</td>
 <td>+28,413</td>
 <td>1,546,687</td>
 <td>+24</td>
 <td>201,245,559</td>
 <td>+19,969</td>
 <td>14,831,044</td>
 <td>15,334</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>249,411,422</td>
 <td>+4,784</td>
 <td>2,061,621</td>
 <td>+17</td>
 <td>245,413,020</td>
 <td>+16,689</td>
 <td>1,936,781</td>
 <td>5,731</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>68,738,704</td>
 <td>+1,494</td>
 <td>1,356,298</td>
 <td>+17</td>
 <td>66,474,004</td>
 <td>+830</td>
 <td>908,402</td>
 <td>10,113</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,378,181</td>
 <td>+1</td>
 <td>28,093</td>
 <td></td>
 <td>14,200,923</td>
 <td>+1</td>
 <td>149,165</td>
 <td>99</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,823,876</td>
 <td>+6</td>
 <td>258,777</td>
 <td></td>
 <td>12,085,577</td>
 <td>+3</td>
 <td>479,522</td>
 <td>548</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>689,728,377</td>
 <td>+38,814</td>
 <td>6,885,457</td>
 <td>+87</td>
 <td>662,070,197</td>
 <td>+46,148</td>
 <td>20,772,723</td>
 <td>38,024</td>
 <td>88,486</td>
 <td>883.3</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">107,123,546</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,970</td>
 <td style="font-weight: bold; text-align:right;">1,165,531                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+20</td>
 <td style="font-weight: bold; text-align:right">105,213,261</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+7,455</td>
 <td style="text-align:right;font-weight:bold;">744,754</td>
 <td style="font-weight: bold; text-align:right">1,033</td>
 <td style="font-weight: bold; text-align:right">319,958</td>
 <td style="font-weight: bold; text-align:right">3,481</td>
 <td style="font-weight: bold; text-align:right">1,180,371,249</td>
 <td style="font-weight: bold; text-align:right">3,525,546</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>287</td><td>0</td>
 <td style="font-weight: bold; text-align:right">9</td>
 <td style="font-weight: bold; text-align:right">0.06</td>
 <td style="font-weight: bold; text-align:right">2,224</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,990,876</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">531,872                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,455,079</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">3,925</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">31,985</td>
 <td style="font-weight: bold; text-align:right">378</td>
 <td style="font-weight: bold; text-align:right">930,414,363</td>
 <td style="font-weight: bold; text-align:right">661,448</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,645</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,090,330</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,735</td>
 <td style="font-weight: bold; text-align:right;">167,311                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,871,393</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+9,003</td>
 <td style="text-align:right;font-weight:bold;">51,626</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">611,277</td>
 <td style="font-weight: bold; text-align:right">2,551</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>392</td><td>0</td>
 <td style="font-weight: bold; text-align:right">57</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">787</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,428,043</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">174,323                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">38,239,600</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">14,120</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">458,112</td>
 <td style="font-weight: bold; text-align:right">2,078</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>481</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">168</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">37,601,257</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">702,907                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">649,189</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">174,602</td>
 <td style="font-weight: bold; text-align:right">3,264</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>306</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,015</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,803,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,694                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">83</td>
 <td style="font-weight: bold; text-align:right">269,169</td>
 <td style="font-weight: bold; text-align:right">595</td>
 <td style="font-weight: bold; text-align:right">100,414,883</td>
 <td style="font-weight: bold; text-align:right">799,578</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,681</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,582</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">31,728,115</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+24,604</td>
 <td style="font-weight: bold; text-align:right;">34,804                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+20</td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">31,373,318</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+17,386</td>
 <td style="text-align:right;font-weight:bold;">319,993</td>
 <td style="font-weight: bold; text-align:right">166</td>
 <td style="font-weight: bold; text-align:right">618,122</td>
 <td style="font-weight: bold; text-align:right">678</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>1,475</td><td>3</td>
 <td style="font-weight: bold; text-align:right">479</td>
 <td style="font-weight: bold; text-align:right">0.4</td>
 <td style="font-weight: bold; text-align:right">6,234</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,857,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">190,392                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">25,545,397</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">121,783</td>
 <td style="font-weight: bold; text-align:right">75</td>
 <td style="font-weight: bold; text-align:right">429,080</td>
 <td style="font-weight: bold; text-align:right">3,159</td>
 <td style="font-weight: bold; text-align:right">272,596,017</td>
 <td style="font-weight: bold; text-align:right">4,523,456</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>317</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,021</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,603,076</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">225,324                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,370,933</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,597</td>
 <td style="text-align:right;font-weight:bold;">6,819</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">359,180</td>
 <td style="font-weight: bold; text-align:right">3,290</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>304</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">100</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">22,929,149</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">399,057                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">22,361,277</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">168,815</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">157,258</td>
 <td style="font-weight: bold; text-align:right">2,737</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>

In [5]:
data = []
for tag in tags:
    print(tag.text)

#
Country,Other
TotalCases
NewCases
TotalDeaths
NewDeaths
TotalRecovered
NewRecovered
ActiveCases
Serious,Critical
Tot Cases/1M pop
Deaths/1M pop
TotalTests
Tests/
1M pop

Population
Continent
1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl
New Cases/1M pop
New Deaths/1M pop
Active Cases/1M pop




North America

126,752,183
+4,116
1,633,966
+29
122,650,408
+8,656
2,467,809
6,199





North America














Asia

217,623,290
+28,413
1,546,687
+24
201,245,559
+19,969
14,831,044
15,334





Asia














Europe

249,411,422
+4,784
2,061,621
+17
245,413,020
+16,689
1,936,781
5,731





Europe














South America

68,738,704
+1,494
1,356,298
+17
66,474,004
+830
908,402
10,113





South America














Oceania

14,378,181
+1
28,093

14,200,923
+1
149,165
99





Australia/Oceania














Africa

12,823,876
+6
258,777

12,085,577
+3
479,522
548





Africa
















721

15

706

0
0



















World
689,728,377
+38,814
6,885,457
+87
662,070,197
+46,148
20,772,723
38,024
88,486
883.3



All












1
USA
107,123,546
+2,970
1,165,531
+20
105,213,261
+7,455
744,754
1,033
319,958
3,481
1,180,371,249
3,525,546
334,805,269
North America

32870
9
0.06
2,224


2
India
44,990,876

531,872

44,455,079

3,925
N/A
31,985
378
930,414,363
661,448
1,406,631,776
Asia

312,6452


3


3
France
40,090,330
+3,735
167,311

39,871,393
+9,003
51,626
869
611,277
2,551
271,490,188
4,139,547
65,584,518
Europe

23920
57

787


4
Germany
38,428,043

174,323

38,239,600

14,120
N/A
458,112
2,078
122,332,384
1,458,359
83,883,596
Europe

24811


168


5
Brazil
37,601,257

702,907

36,249,161

649,189
N/A
174,602
3,264
63,776,166
296,146
215,353,593
South America

63063


3,015


6
Japan
33,803,572

74,694

N/A
N/A
N/A
83
269,169
595
100,414,883
799,578
125,584,838
Asia

41,6811


95,582


7
S. Korea
31,728,115
+24,604
34,804
+20
31,373,318
+17,386
319,993
166
618,122
678
15,804,065
307,892
51,329,899
Asia

21,4753
479
0.4
6,234


8
Italy
25,857,572

190,392

25,545,397

121,783
75
429,080
3,159
272,596,017
4,523,456
60,262,770
Europe

23170


2,021


9
UK
24,603,076

225,324

24,370,933
+1,597
6,819
N/A
359,180
3,290
522,526,476
7,628,357
68,497,907
Europe

33040


100


10
Russia
22,929,149

399,057

22,361,277

168,815
N/A
157,258
2,737
273,400,000
1,875,095
145,805,947
Europe

63651


1,158


11
Turkey
17,232,066

102,174

N/A
N/A
N/A

201,399
1,194
162,743,369
1,902,052
85,561,976
Asia

58371


4,024


12
Spain
13,868,227

121,213

13,697,426

49,588
231
296,843
2,595
471,036,328
10,082,298
46,719,142
Europe

33850


1,061


13
Vietnam
11,613,559
+951
43,206

10,638,370
+202
931,983
42
117,364
437
85,826,548
867,342
98,953,541
Asia

92,2901
10

9,418


14
Australia
11,585,286

20,879

11,526,959

37,448
71
444,412
801
81,916,639
3,142,326
26,068,792
Australia/Oceania

21,2490


1,437


15
Taiwan
10,239,998

19,005

10,220,993

0

428,656
796
30,742,304
1,286,903
23,888,595
Asia

21,2571





16
Argentina
10,054,251

130,509

9,923,097

645
363
218,522
2,837
35,716,069
776,264
46,010,234
South America

53531


14


17
Netherlands
8,610,372

22,992

8,587,380

0
53
500,270
1,336
25,984,435
1,509,718
17,211,447
Europe

27491





18
Mexico
7,621,062
+899
334,167
+9
6,869,584
+1,086
417,311
N/A
57,927
2,540
20,013,810
152,124
131,562,772
North America

173947
7
0.07
3,172


19
Iran
7,611,743

146,257

7,366,014

99,472
137
88,485
1,700
56,669,149
658,769
86,022,837
Asia

115882


1,156


20
Indonesia
6,807,878
+365
161,773
+2
6,633,617
+325
12,488
N/A
24,389
580
114,158,919
408,975
279,134,505
Asia

411,7252
1
0.01
45


21
Poland
6,517,003
+88
119,615
+5
5,335,940

1,061,448
185
172,683
3,169
38,742,389
1,026,566
37,739,785
Europe

63161
2
0.1
28,125


22
Colombia
6,368,934
+1,334
142,765
+17
6,189,718
+751
36,451
342
123,638
2,771
36,951,507
717,327
51,512,762
South America

83611
26
0.3
708


23
Austria
6,077,443
+290
22,507

6,049,453
+171
5,483
14
670,303
2,482
211,273,524
23,302,116
9,066,710
Europe

14030
32

605


24
Greece
6,067,218

36,969

6,016,247
+4,324
14,002
115
588,100
3,583
102,228,365
9,909,078
10,316,637
Europe

22790


1,357


25
Portugal
5,588,310

26,759

5,556,228

5,323
61
551,084
2,639
46,139,518
4,549,993
10,140,570
Europe

23790


525


26
Ukraine
5,553,031

112,352

5,432,654

8,025

128,566
2,601
32,603,805
754,855
43,192,122
Europe

83841


186


27
Chile
5,287,504
+60
64,497

5,222,878
+36
129
23
274,673
3,350
49,680,986
2,580,804
19,250,195
South America

42980
3

7


28
Malaysia
5,100,249

37,087

5,044,652

18,510
36
153,710
1,118
68,352,292
2,059,978
33,181,072
Asia

78950


558


29
Israel
4,826,031

12,527

4,798,473

15,031
21
517,481
1,343
41,373,364
4,436,346
9,326,000
Asia

27440


1,612


30
Belgium
4,799,107

34,336

4,760,035
+236
4,736
43
411,295
2,943
37,018,657
3,172,590
11,668,278
Europe

23400


406


31
DPRK
4,772,813

74

4,772,739

0

183,636
3


25,990,679
Asia

5351,225





32
Thailand
4,738,988

34,053

4,692,636

12,299
N/A
67,624
486
17,270,775
246,450
70,078,203
Asia

152,0584


176


33
Canada
4,676,878

52,425

4,588,876

35,577
99
121,830
1,366
66,343,123
1,728,207
38,388,419
North America

87321


927


34
Czechia
4,642,155
+38
42,804

4,598,570
+33
781

432,360
3,987
57,214,069
5,328,790
10,736,784
Europe

22510
4

73


35
Peru
4,507,363

220,673

4,284,940

1,750
26
133,812
6,551
38,548,796
1,144,417
33,684,208
South America

71531


52


36
Switzerland
4,405,938

14,452

4,389,039

2,447
39
502,179
1,647
23,833,472
2,716,487
8,773,637
Europe

26070


279


37
Philippines
4,144,351
+1,537
66,466

4,062,467
+957
15,418
162
36,836
591
35,267,600
313,465
112,508,994
Asia

271,6933
14

137


38
South Africa
4,076,463

102,595

3,912,506

61,362
192
67,095
1,689
26,795,090
441,027
60,756,135
Africa

155922


1,010


39
Romania
3,404,197

68,184

3,329,181

6,832
78
178,873
3,583
27,516,705
1,445,863
19,031,335
Europe

62791


359


40
Denmark
3,181,900
+22
8,708
+3
3,172,759

433
5
545,317
1,492
129,287,322
22,157,400
5,834,950
Europe

26700
4
0.5
74


41
Hong Kong
2,904,315

13,819

2,875,092
+336
15,404
28
381,931
1,817
76,127,725
10,011,143
7,604,299
Asia

35500


2,026


42
Sweden
2,710,457

24,389

2,683,140
+307
2,928
8
265,238
2,387
19,500,873
1,908,301
10,218,971
Europe

44191


287


43
Serbia
2,542,012
+309
18,053
+1
2,520,603
+110
3,356
6
293,772
2,086
12,939,760
1,495,405
8,653,016
Europe

34791
36
0.1
388


44
Singapore
2,472,873

1,727

2,149,583

321,563
2
416,060
291
24,756,666
4,165,302
5,943,546
Asia

23,4420


54,103


45
Iraq
2,465,545

25,375

2,439,497

673
21
58,474
602
19,544,451
463,523
42,164,965
Asia

171,6622


16


46
New Zealand
2,375,191

4,362

2,358,376

12,453

484,911
891
7,768,604
1,586,011
4,898,203
Australia/Oceania

21,1231


2,542


47
Hungary
2,202,887
+171
48,873
+5
2,151,825
+526
2,189
2
229,318
5,088
11,394,556
1,186,160
9,606,259
Europe

41971
18
0.5
228


48
Bangladesh
2,039,244

29,446

1,998,448

11,350
N/A
12,147
175
15,254,399
90,862
167,885,689
Asia

825,70111


68


49
Slovakia
1,866,857

21,167

1,845,578

112
11
341,903
3,877
7,432,749
1,361,261
5,460,193
Europe

32581


21


50
Georgia
1,842,046

17,070

1,776,548

48,428

464,139
4,301
16,920,079
4,263,340
3,968,738
Asia

22320


12,202


51
Jordan
1,746,997

14,122

1,731,007

1,868
59
169,597
1,371
17,201,885
1,669,945
10,300,869
Asia

67291


181


52
Ireland
1,712,113

8,960

1,701,342

1,811
19
341,045
1,785
13,083,449
2,606,161
5,020,199
Europe

35600


361


53
Pakistan
1,581,038
+5
30,660

1,538,689

11,689
7
6,889
134
30,571,377
133,215
229,488,994
Asia

1457,4858
0.02

51


54
Norway
1,484,882

5,435

1,478,204

1,243
20
269,422
986
11,002,430
1,996,315
5,511,370
Europe

41,0141


226


55
Finland
1,480,370

9,750

1,466,950
+291
3,670
21
266,495
1,755
12,101,220
2,178,453
5,554,960
Europe

45700


661


56
Kazakhstan
1,411,831

13,848

1,383,020

14,963
24
73,514
721
11,575,012
602,707
19,205,043
Asia

141,3872


779


57
Slovenia
1,344,023
+19
7,100

1,328,006

8,917
8
646,776
3,417
2,847,701
1,370,382
2,078,034
Europe

22931
9

4,291


58
Lithuania
1,320,534
+31
9,684

1,309,711
+71
1,139
1
496,123
3,638
10,453,692
3,927,438
2,661,708
Europe

22750
12

428


59
Bulgaria
1,307,678
+81
38,388
+3
1,267,371
+84
1,919
31
191,053
5,609
11,238,787
1,641,994
6,844,597
Europe

51781
12
0.4
280


60
Morocco
1,274,180

16,297

1,256,151

1,732
3
33,733
431
13,001,033
344,191
37,772,756
Africa

302,3183


46


61
Croatia
1,273,795

18,255

1,255,288

252
6
313,798
4,497
5,603,151
1,380,329
4,059,286
Europe

32221


62


62
Guatemala
1,252,899
+209
20,201

1,230,457
+80
2,241
5
67,418
1,087
7,342,086
395,075
18,584,039
North America

159203
11

121


63
Lebanon
1,237,556

10,914

1,087,587

139,055
74
185,128
1,633
4,795,578
717,380
6,684,849
Asia

56131


20,802


64
Costa Rica
1,232,576

9,374

860,711

362,491
52
237,841
1,809
4,659,757
899,158
5,182,354
North America

45531


69,947


65
Bolivia
1,199,346
+100
22,384

1,168,509
+43
8,453
220
100,007
1,866
2,710,261
225,993
11,992,656
South America

105364
8

705


66
Tunisia
1,153,323

29,420

N/A
N/A
N/A
44
95,738
2,442
5,012,932
416,126
12,046,656
Africa

104092


1,154


67
Cuba
1,114,241
+38
8,530

1,105,534
+35
177
2
98,556
754
14,345,279
1,268,859
11,305,652
North America

101,3251
3

16


68
UAE
1,067,030

2,349

1,054,525

10,156

105,837
233
200,732,262
19,910,389
10,081,785
Asia

94,2920


1,007


69
Ecuador
1,062,275

36,019

1,025,081

1,175
759
58,646
1,989
3,082,403
170,173
18,113,361
South America

175036


65


70
Panama
1,040,230

8,624

1,030,855

751
16
233,919
1,939
7,697,189
1,730,886
4,446,964
North America

45161


169


71
Uruguay
1,038,774

7,634

1,030,944

196
18
297,131
2,184
6,114,822
1,749,083
3,496,016
South America

34581


56


72
Mongolia
1,008,655

2,179

1,006,086
+227
390
192
298,588
645
4,030,048
1,193,000
3,378,078
Asia

31,5501


115


73
Nepal
1,003,340
+3
12,031

991,287
+4
22

33,195
398
6,045,812
200,023
30,225,582
Asia

302,5125
0.10

0.7


74
Belarus
994,037

7,118

985,592

1,327

105,381
755
13,646,641
1,446,722
9,432,800
Europe

91,3251


141


75
Latvia
977,891

6,344

971,406

141
13
528,922
3,431
7,875,835
4,259,886
1,848,837
Europe

22910


76


76
Saudi Arabia
841,469

9,646

827,923

3,900
66
23,475
269
45,481,735
1,268,848
35,844,909
Asia

433,7161


109


77
Azerbaijan
831,849
+15
10,274

821,516
+16
59

80,760
997
7,623,270
740,109
10,300,205
Asia

121,0031
1

6


78
Paraguay
810,581

19,931

N/A
N/A
N/A
7
110,950
2,728
2,657,506
363,751
7,305,843
South America

93673


12,638


79
Bahrain
721,923
+32
1,564

720,141
+32
218
2
404,669
877
10,855,063
6,084,735
1,783,983
Asia

21,1410
18

122


80
Sri Lanka
672,467
+8
16,873
+1
655,556
+15
38

31,168
782
6,486,117
300,619
21,575,842
Asia

321,2793
0.4
0.05
2


81
Kuwait
665,931

2,570

660,237

3,124

152,028
587
8,455,743
1,930,391
4,380,326
Asia

71,7041


713


82
Dominican Republic
661,176

4,384

644,785

12,007
4
59,800
397
3,740,928
338,350
11,056,370
North America

172,5223


1,086


83
Cyprus
660,854

1,364

659,490

0
60
540,184
1,115
9,640,118
7,879,860
1,223,387
Asia

28970





84
Myanmar
638,980
+91
19,494

617,981
+89
1,505

11,570
353
10,657,186
192,970
55,227,143
Asia

862,8335
2

27


85
Palestine
621,008

5,404

615,445

159
17
116,173
1,011
3,078,533
575,907
5,345,541
Asia

99892


30


86
Moldova
620,574

12,118

504,142

104,314
49
154,634
3,020
3,216,305
801,437
4,013,171
Europe

63311


25,993


87
Estonia
618,931

3,001

524,990

90,940
2
468,210
2,270
3,716,945
2,811,799
1,321,910
Europe

24400


68,794


88
Venezuela
552,695

5,856

546,537

302
31
18,885
200
3,359,014
114,771
29,266,991
South America

534,9989


10


89
Egypt
516,023

24,613

442,182

49,228
122
4,861
232
3,693,367
34,792
106,156,692
Africa

2064,31329


464


90
Qatar
513,500

690

512,402

408
30
172,320
232
4,065,369
1,364,257
2,979,915
Asia

64,3191


137


91
Libya
507,263

6,437

500,825

1

72,047
914
2,483,848
352,782
7,040,745
Africa

141,0943


0.1


92
Ethiopia
500,902
+3
7,574

488,131
+1
5,197
1
4,146
63
5,553,439
45,967
120,812,698
Africa

24115,95122
0.02

43


93
Réunion
486,588

921

418,572

67,095
10
535,854
1,014
1,603,660
1,766,027
908,061
Africa

29861


73,888


94
Honduras
472,619

11,116

N/A
N/A
N/A
105
46,239
1,088
1,660,662
162,472
10,221,247
North America

229206


32,184


95
Armenia
449,203

8,750

435,162

5,291

151,147
2,944
3,242,901
1,091,164
2,971,966
Asia

73401


1,780


96
Bosnia and Herzegovina
402,998

16,347

379,084

7,567

124,025
5,031
1,884,721
580,036
3,249,317
Europe

81992


2,329


97
Oman
399,449

4,628

384,669

10,152
2
75,028
869
25,000,000
4,695,724
5,323,993
Asia

131,1500


1,907


98
North Macedonia
348,281

9,677

337,068

1,536

167,338
4,649
2,226,216
1,069,626
2,081,304
Europe

62151


738


99
Zambia
343,995

4,058

339,858

79

17,668
208
4,047,915
207,903
19,470,234
Africa

574,7985


4


100
Kenya
343,074

5,688

337,309

77
1
6,103
101
3,967,062
70,569
56,215,221
Africa

1649,88314


1


101
Albania
334,726

3,602

329,428

1,696

116,777
1,257
1,941,032
677,173
2,866,374
Europe

97961


592


102
Botswana
329,905

2,801

327,049

55
1
135,143
1,147
2,026,898
830,300
2,441,162
Africa

78721


23


103
Luxembourg
319,959

1,232

316,690

2,037

498,091
1,918
4,587,145
7,140,959
642,371
Europe

25210


3,171


104
Brunei
306,333

225

243,601

62,507
3
687,723
505
717,784
1,611,437
445,431
Asia

11,9801


140,329


105
Montenegro
291,898

2,828

288,569

501
6
464,843
4,504
2,756,486
4,389,658
627,950
Europe

22220


798


106
Algeria
271,841
+3
6,881

183,053
+2
81,907

5,994
152
230,960
5,093
45,350,148
Africa

1676,591196
0.07

1,806


107
Nigeria
266,675

3,155

259,953

3,567
11
1,230
15
5,708,974
26,339
216,746,934
Africa

81368,70038


16


108
Zimbabwe
265,030

5,695

258,888

447
12
17,287
371
2,525,756
164,744
15,331,428
Africa

582,6926


29


109
Uzbekistan
253,662

1,637

241,486

10,539
23
7,378
48
1,377,915
40,077
34,382,084
Asia

13621,00325


307


110
Mozambique
233,417

2,243

228,805

2,369
11
7,054
68
1,371,127
41,437
33,089,461
Africa

14214,75224


72


111
Martinique
229,975

1,102

N/A
N/A
N/A
12
614,763
2,946
828,928
2,215,870
374,087
North America

23390


611,540


112
Afghanistan
221,822
+106
7,915
+1
197,942
+380
15,965
45
5,443
194
1,262,617
30,981
40,754,388
Asia

1845,14932
3
0.02
392


113
Laos
218,247
+20
758

N/A
N/A
N/A

29,173
101
1,233,207
164,845
7,481,023
Asia

349,8696
3

28,048


114
Iceland
209,191

229

N/A
N/A
N/A
2
605,661
663
1,996,384
5,780,036
345,393
Europe

21,5080


385,871


115
Kyrgyzstan
206,890

2,991

196,406

7,493
131
30,749
445
1,907,195
283,460
6,728,271
Asia

332,2504


1,114


116
Guadeloupe
202,836

1,017

N/A
N/A
N/A
19
507,351
2,544
938,039
2,346,306
399,794
North America

23930


499,180


117
El Salvador
201,785

4,230

179,410

18,145
8
30,805
646
2,610,114
398,467
6,550,389
North America

321,5493


2,770


118
Trinidad and Tobago
191,496

4,390

187,078

28
8
136,143
3,121
913,289
649,295
1,406,585
North America

73202


20


119
Maldives
186,651

315

163,687

22,649
25
345,021
582
2,213,831
4,092,223
540,985
Asia

31,7170


41,866


120
Ghana
171,657

1,462

170,161

34
2
5,299
45
2,536,496
78,298
32,395,450
Africa

18922,15813


1


121
Namibia
171,310

4,091

167,099

120

65,041
1,553
1,062,663
403,460
2,633,874
Africa

156442


46


122
Uganda
170,775

3,632

100,431

66,712
3
3,526
75
3,012,408
62,198
48,432,863
Africa

28413,33516


1,377


123
Jamaica
154,993

3,549

102,964

48,480

51,922
1,189
1,183,986
396,633
2,985,094
North America

198413


16,241


124
Cambodia
138,781

3,056

135,689

36

8,083
178
3,091,420
180,062
17,168,639
Asia

1245,6186


2


125
Rwanda
133,194

1,468

131,647

79

9,793
108
6,021,981
442,778
13,600,464
Africa

1029,2652


6


126
Cameroon
125,036

1,972

122,807

257
13
4,480
71
1,751,774
62,762
27,911,548
Africa

22314,15416


9


127
Malta
118,756

837

117,365

554
4
267,449
1,885
2,139,366
4,818,034
444,033
Europe

45310


1,248


128
Barbados
107,794

593

106,971

230

374,255
2,059
801,451
2,782,594
288,023
North America

34860


799


129
Angola
105,384

1,934

103,419

31

3,009
55
1,499,795
42,818
35,027,343
Africa

33218,11123


0.9


130
Channel Islands
101,717

228

101,321

168

576,421
1,292
1,252,808
7,099,551
176,463
Europe

27740


952


131
French Guiana
98,041

420

11,254

86,367
6
312,065
1,337
651,257
2,072,951
314,169
South America

37480


274,906


132
DRC
96,652

1,467

84,489

10,696

1,015
15
846,704
8,890
95,240,792
Africa

98564,922112


112


133
Senegal
88,997

1,971

87,024

2

5,041
112
1,146,543
64,946
17,653,671
Africa

1988,95715


0.1


134
Malawi
88,728

2,686

85,651

391
67
4,397
133
624,784
30,959
20,180,839
Africa

2277,51332


19


135
Ivory Coast
88,331

835

87,497

-1

3,184
30
1,690,934
60,951
27,742,298
Africa

31433,22416


-0.04


136
Suriname
82,513

1,405

N/A
N/A
N/A

138,252
2,354
241,842
405,210
596,831
South America

74252


52,527


137
New Caledonia
79,922

314

79,605

3
9
274,726
1,079
98,964
340,182
290,915
Australia/Oceania

49263


10


138
French Polynesia
78,581

649

N/A
N/A
N/A
7
276,534
2,284


284,164
Australia/Oceania

4438


156,360


139
Eswatini
74,670

1,425

73,116

129

63,022
1,203
1,048,704
885,119
1,184,817
Africa

168311


109


140
Guyana
73,240

1,298

71,880

62

92,237
1,635
729,688
918,950
794,045
South America

116121


78


141
Belize
70,782

688

70,085

9
6
171,722
1,669
576,016
1,397,453
412,190
North America

65991


22


142
Fiji
68,921

883

67,029

1,009

75,782
971
670,903
737,689
909,466
Australia/Oceania

131,0301


1,109


143
Madagascar
68,288

1,425

66,854

9

2,340
49
531,218
18,206
29,178,077
Africa

42720,47655


0.3


144
Sudan
63,993

5,046

58,683

264

1,391
110
562,941
12,240
45,992,020
Africa

7199,11582


6


145
Cabo Verde
63,934

414

63,407

113
23
112,624
729
401,622
707,482
567,678
Africa

91,3711


199


146
Mauritania
63,715

997

62,471

247

12,998
203
1,009,957
206,030
4,901,981
Africa

774,9175


50


147
Bhutan
62,671

21

61,564

1,086

79,538
27
2,303,734
2,923,739
787,941
Asia

1337,5210


1,378


148
Syria
57,608

3,164

54,370

74

2,975
163
146,269
7,553
19,364,809
Asia

3366,120132


4


149
Burundi
53,762

38

53,569

155

4,258
3
345,742
27,386
12,624,840
Africa

235332,23337


12


150
Seychelles
50,937

172

50,750

15

512,311
1,730


99,426
Africa

2578


151


151
Gabon
48,992

307

48,674

11

21,013
132
1,621,909
695,641
2,331,533
Africa

487,5951


5


152
Andorra
48,015

165

47,563

287
14
619,844
2,130
249,838
3,225,256
77,463
Europe

24690


3,705


153
Papua New Guinea
46,864

670

43,982

2,212
7
5,043
72
249,149
26,813
9,292,169
Australia/Oceania

19813,86937


238


154
Curaçao
45,986

295

44,720

971
3
277,812
1,782
496,693
3,000,640
165,529
North America

45610


5,866


155
Aruba
44,180

236

42,438

1,506
2
410,560
2,193
177,885
1,653,068
107,609
North America

24561


13,995


156
Tanzania
43,078

846

N/A
N/A
N/A
7
681
13


63,298,550
Africa

1,46974,821


664


157
Mauritius
42,518

1,049

40,740

729

33,355
823
358,675
281,374
1,274,727
Africa

301,2154


572


158
Mayotte
42,027

188

N/A
N/A
N/A

146,815
657
176,919
618,038
286,259
Africa

71,5232


135,804


159
Togo
39,499

290

39,206

3

4,550
33
811,719
93,507
8,680,837
Africa

22029,93411


0.3


160
Guinea
38,563

468

37,757

338
8
2,781
34
660,107
47,607
13,865,691
Africa

36029,62821


24


161
Bahamas
38,084

844

36,366

874
1
95,087
2,107
257,839
643,767
400,516
North America

114752


2,182


162
Isle of Man
38,008

116

N/A
N/A
N/A

443,335
1,353
150,753
1,758,422
85,732
Europe

27391


129,450


163
Lesotho
34,790

723

25,980

8,087

15,990
332
431,221
198,199
2,175,699
Africa

633,0095


3,717


164
Faeroe Islands
34,658

28

N/A
N/A
N/A
5
703,959
569
778,000
15,802,409
49,233
Europe

11,7580


547,133


165
Haiti
34,246

860

33,361

25

2,932
74
132,422
11,337
11,680,283

In [6]:
data = []
for tag in tags:
    data.append(tag.text)
    
data

['\n#\nCountry,Other\nTotalCases\nNewCases\nTotalDeaths\nNewDeaths\nTotalRecovered\nNewRecovered\nActiveCases\nSerious,Critical\nTot\xa0Cases/1M pop\nDeaths/1M pop\nTotalTests\nTests/\n1M pop\n\nPopulation\nContinent\n1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl\nNew Cases/1M pop\nNew Deaths/1M pop\nActive Cases/1M pop\n',
 '\n\n\nNorth America\n\n126,752,183\n+4,116\n1,633,966\n+29\n122,650,408\n+8,656\n2,467,809\n6,199\n\n\n\n\n\nNorth America\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nAsia\n\n217,623,290\n+28,413\n1,546,687\n+24\n201,245,559\n+19,969\n14,831,044\n15,334\n\n\n\n\n\nAsia\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nEurope\n\n249,411,422\n+4,784\n2,061,621\n+17\n245,413,020\n+16,689\n1,936,781\n5,731\n\n\n\n\n\nEurope\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nSouth America\n\n68,738,704\n+1,494\n1,356,298\n+17\n66,474,004\n+830\n908,402\n10,113\n\n\n\n\n\nSouth America\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nOceania\n\n14,378,181\n+1\n28,093\n\n14,200,923\n+1\n149,165\n99\n\n\n\n\n\nAustralia/Oceania\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nAfrica\n\n12,823,876\n+6\n258,777\n\n12,085,577\n+3\n479,522\n548\n\n\n\n\n\nAfrica\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\n\n\n721\n\n15\n\n706\n\n0\n0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n',
 '\n\nWorld\n689,728,377\n+38,814\n6,885,457\n+87\n662,070,197\n+46,148\n20,772,723\n38,024\n88,486\n883.3\n\n\n\nAll\n\n\n\n\n\n\n\n\n\n\n',
 '\n1\nUSA\n107,123,546\n+2,970\n1,165,531                                \n+20\n105,213,261\n+7,455\n744,754\n1,033\n319,958\n3,481\n1,180,371,249\n3,525,546\n334,805,269 \nNorth America\n\n32870\n9\n0.06\n2,224\n',
 '\n2\nIndia\n44,990,876\n\n531,872                                \n\n44,455,079\n\n3,925\nN/A\n31,985\n378\n930,414,363\n661,448\n1,406,631,776 \nAsia\n\n312,6452\n\n\n3\n',
 '\n3\nFrance\n40,090,330\n+3,735\n167,311                                \n\n39,871,393\n+9,003\n51,626\n869\n611,277\n2,551\n271,490,188\n4,139,547\n65,584,518 \nEurope\n\n23920\n57\n\n787\n',
 '\n4\nGermany\n38,428,043\n\n174,323                                \n\n38,239,600\n\n14,120\nN/A\n458,112\n2,078\n122,332,384\n1,458,359\n83,883,596 \nEurope\n\n24811\n\n\n168\n',
 '\n5\nBrazil\n37,601,257\n\n702,907                                \n\n36,249,161\n\n649,189\nN/A\n174,602\n3,264\n63,776,166\n296,146\n215,353,593 \nSouth America\n\n63063\n\n\n3,015\n',
 '\n6\nJapan\n33,803,572\n\n74,694                                \n\nN/A\nN/A\nN/A\n83\n269,169\n595\n100,414,883\n799,578\n125,584,838 \nAsia\n\n41,6811\n\n\n95,582\n',
 '\n7\nS. Korea\n31,728,115\n+24,604\n34,804                                \n+20\n31,373,318\n+17,386\n319,993\n166\n618,122\n678\n15,804,065\n307,892\n51,329,899 \nAsia\n\n21,4753\n479\n0.4\n6,234\n',
 '\n8\nItaly\n25,857,572\n\n190,392                                \n\n25,545,397\n\n121,783\n75\n429,080\n3,159\n272,596,017\n4,523,456\n60,262,770 \nEurope\n\n23170\n\n\n2,021\n',
 '\n9\nUK\n24,603,076\n\n225,324                                \n\n24,370,933\n+1,597\n6,819\nN/A\n359,180\n3,290\n522,526,476\n7,628,357\n68,497,907 \nEurope\n\n33040\n\n\n100\n',
 '\n10\nRussia\n22,929,149\n\n399,057                                \n\n22,361,277\n\n168,815\nN/A\n157,258\n2,737\n273,400,000\n1,875,095\n145,805,947 \nEurope\n\n63651\n\n\n1,158\n',
 '\n11\nTurkey\n17,232,066\n\n102,174                                \n\nN/A\nN/A\nN/A\n\n201,399\n1,194\n162,743,369\n1,902,052\n85,561,976 \nAsia\n\n58371\n\n\n4,024\n',
 '\n12\nSpain\n13,868,227\n\n121,213                                \n\n13,697,426\n\n49,588\n231\n296,843\n2,595\n471,036,328\n10,082,298\n46,719,142 \nEurope\n\n33850\n\n\n1,061\n',
 '\n13\nVietnam\n11,613,559\n+951\n43,206                                \n\n10,638,370\n+202\n931,983\n42\n117,364\n437\n85,826,548\n867,342\n98,953,541 \nAsia\n\n92,2901\n10\n\n9,418\n',
 '\n14\nAustralia\n11,585,286\n\n20,879                                \n\n11,526,959\n\n37,448\n71\n444,412\n801\n81,916,639\n3,142,326\n26,068,792 \nAustralia/Oceania\n\n21,2490\n\n\n1,437\n',
 '\n15\nTaiwan\n10,239,998\n\n19,005                                \n\n10,220,993\n\n0\n\n428,656\n796\n30,742,304\n1,286,903\n23,888,595 \nAsia\n\n21,2571\n\n\n\n',
 '\n16\nArgentina\n10,054,251\n\n130,509                                \n\n9,923,097\n\n645\n363\n218,522\n2,837\n35,716,069\n776,264\n46,010,234 \nSouth America\n\n53531\n\n\n14\n',
 '\n17\nNetherlands\n8,610,372\n\n22,992                                \n\n8,587,380\n\n0\n53\n500,270\n1,336\n25,984,435\n1,509,718\n17,211,447 \nEurope\n\n27491\n\n\n\n',
 '\n18\nMexico\n7,621,062\n+899\n334,167                                \n+9\n6,869,584\n+1,086\n417,311\nN/A\n57,927\n2,540\n20,013,810\n152,124\n131,562,772 \nNorth America\n\n173947\n7\n0.07\n3,172\n',
 '\n19\nIran\n7,611,743\n\n146,257                                \n\n7,366,014\n\n99,472\n137\n88,485\n1,700\n56,669,149\n658,769\n86,022,837 \nAsia\n\n115882\n\n\n1,156\n',
 '\n20\nIndonesia\n6,807,878\n+365\n161,773                                \n+2\n6,633,617\n+325\n12,488\nN/A\n24,389\n580\n114,158,919\n408,975\n279,134,505 \nAsia\n\n411,7252\n1\n0.01\n45\n',
 '\n21\nPoland\n6,517,003\n+88\n119,615                                \n+5\n5,335,940\n\n1,061,448\n185\n172,683\n3,169\n38,742,389\n1,026,566\n37,739,785 \nEurope\n\n63161\n2\n0.1\n28,125\n',
 '\n22\nColombia\n6,368,934\n+1,334\n142,765                                \n+17\n6,189,718\n+751\n36,451\n342\n123,638\n2,771\n36,951,507\n717,327\n51,512,762 \nSouth America\n\n83611\n26\n0.3\n708\n',
 '\n23\nAustria\n6,077,443\n+290\n22,507                                \n\n6,049,453\n+171\n5,483\n14\n670,303\n2,482\n211,273,524\n23,302,116\n9,066,710 \nEurope\n\n14030\n32\n\n605\n',
 '\n24\nGreece\n6,067,218\n\n36,969                                \n\n6,016,247\n+4,324\n14,002\n115\n588,100\n3,583\n102,228,365\n9,909,078\n10,316,637 \nEurope\n\n22790\n\n\n1,357\n',
 '\n25\nPortugal\n5,588,310\n\n26,759                                \n\n5,556,228\n\n5,323\n61\n551,084\n2,639\n46,139,518\n4,549,993\n10,140,570 \nEurope\n\n23790\n\n\n525\n',
 '\n26\nUkraine\n5,553,031\n\n112,352                                \n\n5,432,654\n\n8,025\n\n128,566\n2,601\n32,603,805\n754,855\n43,192,122 \nEurope\n\n83841\n\n\n186\n',
 '\n27\nChile\n5,287,504\n+60\n64,497                                \n\n5,222,878\n+36\n129\n23\n274,673\n3,350\n49,680,986\n2,580,804\n19,250,195 \nSouth America\n\n42980\n3\n\n7\n',
 '\n28\nMalaysia\n5,100,249\n\n37,087                                \n\n5,044,652\n\n18,510\n36\n153,710\n1,118\n68,352,292\n2,059,978\n33,181,072 \nAsia\n\n78950\n\n\n558\n',
 '\n29\nIsrael\n4,826,031\n\n12,527                                \n\n4,798,473\n\n15,031\n21\n517,481\n1,343\n41,373,364\n4,436,346\n9,326,000 \nAsia\n\n27440\n\n\n1,612\n',
 '\n30\nBelgium\n4,799,107\n\n34,336                                \n\n4,760,035\n+236\n4,736\n43\n411,295\n2,943\n37,018,657\n3,172,590\n11,668,278 \nEurope\n\n23400\n\n\n406\n',
 '\n31\nDPRK\n4,772,813\n\n74                                \n\n4,772,739\n\n0\n\n183,636\n3\n\n\n25,990,679 \nAsia\n\n5351,225\n\n\n\n',
 '\n32\nThailand\n4,738,988\n\n34,053                                \n\n4,692,636\n\n12,299\nN/A\n67,624\n486\n17,270,775\n246,450\n70,078,203 \nAsia\n\n152,0584\n\n\n176\n',
 '\n33\nCanada\n4,676,878\n\n52,425                                \n\n4,588,876\n\n35,577\n99\n121,830\n1,366\n66,343,123\n1,728,207\n38,388,419 \nNorth America\n\n87321\n\n\n927\n',
 '\n34\nCzechia\n4,642,155\n+38\n42,804                                \n\n4,598,570\n+33\n781\n\n432,360\n3,987\n57,214,069\n5,328,790\n10,736,784 \nEurope\n\n22510\n4\n\n73\n',
 '\n35\nPeru\n4,507,363\n\n220,673                                \n\n4,284,940\n\n1,750\n26\n133,812\n6,551\n38,548,796\n1,144,417\n33,684,208 \nSouth America\n\n71531\n\n\n52\n',
 '\n36\nSwitzerland\n4,405,938\n\n14,452                                \n\n4,389,039\n\n2,447\n39\n502,179\n1,647\n23,833,472\n2,716,487\n8,773,637 \nEurope\n\n26070\n\n\n279\n',
 '\n37\nPhilippines\n4,144,351\n+1,537\n66,466                                \n\n4,062,467\n+957\n15,418\n162\n36,836\n591\n35,267,600\n313,465\n112,508,994 \nAsia\n\n271,6933\n14\n\n137\n',
 '\n38\nSouth Africa\n4,076,463\n\n102,595                                \n\n3,912,506\n\n61,362\n192\n67,095\n1,689\n26,795,090\n441,027\n60,756,135 \nAfrica\n\n155922\n\n\n1,010\n',
 '\n39\nRomania\n3,404,197\n\n68,184                                \n\n3,329,181\n\n6,832\n78\n178,873\n3,583\n27,516,705\n1,445,863\n19,031,335 \nEurope\n\n62791\n\n\n359\n',
 '\n40\nDenmark\n3,181,900\n+22\n8,708                                \n+3\n3,172,759\n\n433\n5\n545,317\n1,492\n129,287,322\n22,157,400\n5,834,950 \nEurope\n\n26700\n4\n0.5\n74\n',
 '\n41\nHong Kong\n2,904,315\n\n13,819                                \n\n2,875,092\n+336\n15,404\n28\n381,931\n1,817\n76,127,725\n10,011,143\n7,604,299 \nAsia\n\n35500\n\n\n2,026\n',
 '\n42\nSweden\n2,710,457\n\n24,389                                \n\n2,683,140\n+307\n2,928\n8\n265,238\n2,387\n19,500,873\n1,908,301\n10,218,971 \nEurope\n\n44191\n\n\n287\n',
 '\n43\nSerbia\n2,542,012\n+309\n18,053                                \n+1\n2,520,603\n+110\n3,356\n6\n293,772\n2,086\n12,939,760\n1,495,405\n8,653,016 \nEurope\n\n34791\n36\n0.1\n388\n',
 '\n44\nSingapore\n2,472,873\n\n1,727                                \n\n2,149,583\n\n321,563\n2\n416,060\n291\n24,756,666\n4,165,302\n5,943,546 \nAsia\n\n23,4420\n\n\n54,103\n',
 '\n45\nIraq\n2,465,545\n\n25,375                                \n\n2,439,497\n\n673\n21\n58,474\n602\n19,544,451\n463,523\n42,164,965 \nAsia\n\n171,6622\n\n\n16\n',
 '\n46\nNew Zealand\n2,375,191\n\n4,362                                \n\n2,358,376\n\n12,453\n\n484,911\n891\n7,768,604\n1,586,011\n4,898,203 \nAustralia/Oceania\n\n21,1231\n\n\n2,542\n',
 '\n47\nHungary\n2,202,887\n+171\n48,873                                \n+5\n2,151,825\n+526\n2,189\n2\n229,318\n5,088\n11,394,556\n1,186,160\n9,606,259 \nEurope\n\n41971\n18\n0.5\n228\n',
 '\n48\nBangladesh\n2,039,244\n\n29,446                                \n\n1,998,448\n\n11,350\nN/A\n12,147\n175\n15,254,399\n90,862\n167,885,689 \nAsia\n\n825,70111\n\n\n68\n',
 '\n49\nSlovakia\n1,866,857\n\n21,167                                \n\n1,845,578\n\n112\n11\n341,903\n3,877\n7,432,749\n1,361,261\n5,460,193 \nEurope\n\n32581\n\n\n21\n',
 '\n50\nGeorgia\n1,842,046\n\n17,070                                \n\n1,776,548\n\n48,428\n\n464,139\n4,301\n16,920,079\n4,263,340\n3,968,738 \nAsia\n\n22320\n\n\n12,202\n',
 '\n51\nJordan\n1,746,997\n\n14,122                                \n\n1,731,007\n\n1,868\n59\n169,597\n1,371\n17,201,885\n1,669,945\n10,300,869 \nAsia\n\n67291\n\n\n181\n',
 '\n52\nIreland\n1,712,113\n\n8,960                                \n\n1,701,342\n\n1,811\n19\n341,045\n1,785\n13,083,449\n2,606,161\n5,020,199 \nEurope\n\n35600\n\n\n361\n',
 '\n53\nPakistan\n1,581,038\n+5\n30,660                                \n\n1,538,689\n\n11,689\n7\n6,889\n134\n30,571,377\n133,215\n229,488,994 \nAsia\n\n1457,4858\n0.02\n\n51\n',
 '\n54\nNorway\n1,484,882\n\n5,435                                \n\n1,478,204\n\n1,243\n20\n269,422\n986\n11,002,430\n1,996,315\n5,511,370 \nEurope\n\n41,0141\n\n\n226\n',
 '\n55\nFinland\n1,480,370\n\n9,750                                \n\n1,466,950\n+291\n3,670\n21\n266,495\n1,755\n12,101,220\n2,178,453\n5,554,960 \nEurope\n\n45700\n\n\n661\n',
 '\n56\nKazakhstan\n1,411,831\n\n13,848                                \n\n1,383,020\n\n14,963\n24\n73,514\n721\n11,575,012\n602,707\n19,205,043 \nAsia\n\n141,3872\n\n\n779\n',
 '\n57\nSlovenia\n1,344,023\n+19\n7,100                                \n\n1,328,006\n\n8,917\n8\n646,776\n3,417\n2,847,701\n1,370,382\n2,078,034 \nEurope\n\n22931\n9\n\n4,291\n',
 '\n58\nLithuania\n1,320,534\n+31\n9,684                                \n\n1,309,711\n+71\n1,139\n1\n496,123\n3,638\n10,453,692\n3,927,438\n2,661,708 \nEurope\n\n22750\n12\n\n428\n',
 '\n59\nBulgaria\n1,307,678\n+81\n38,388                                \n+3\n1,267,371\n+84\n1,919\n31\n191,053\n5,609\n11,238,787\n1,641,994\n6,844,597 \nEurope\n\n51781\n12\n0.4\n280\n',
 '\n60\nMorocco\n1,274,180\n\n16,297                                \n\n1,256,151\n\n1,732\n3\n33,733\n431\n13,001,033\n344,191\n37,772,756 \nAfrica\n\n302,3183\n\n\n46\n',
 '\n61\nCroatia\n1,273,795\n\n18,255                                \n\n1,255,288\n\n252\n6\n313,798\n4,497\n5,603,151\n1,380,329\n4,059,286 \nEurope\n\n32221\n\n\n62\n',
 '\n62\nGuatemala\n1,252,899\n+209\n20,201                                \n\n1,230,457\n+80\n2,241\n5\n67,418\n1,087\n7,342,086\n395,075\n18,584,039 \nNorth America\n\n159203\n11\n\n121\n',
 '\n63\nLebanon\n1,237,556\n\n10,914                                \n\n1,087,587\n\n139,055\n74\n185,128\n1,633\n4,795,578\n717,380\n6,684,849 \nAsia\n\n56131\n\n\n20,802\n',
 '\n64\nCosta Rica\n1,232,576\n\n9,374                                \n\n860,711\n\n362,491\n52\n237,841\n1,809\n4,659,757\n899,158\n5,182,354 \nNorth America\n\n45531\n\n\n69,947\n',
 '\n65\nBolivia\n1,199,346\n+100\n22,384                                \n\n1,168,509\n+43\n8,453\n220\n100,007\n1,866\n2,710,261\n225,993\n11,992,656 \nSouth America\n\n105364\n8\n\n705\n',
 '\n66\nTunisia\n1,153,323\n\n29,420                                \n\nN/A\nN/A\nN/A\n44\n95,738\n2,442\n5,012,932\n416,126\n12,046,656 \nAfrica\n\n104092\n\n\n1,154\n',
 '\n67\nCuba\n1,114,241\n+38\n8,530                                \n\n1,105,534\n+35\n177\n2\n98,556\n754\n14,345,279\n1,268,859\n11,305,652 \nNorth America\n\n101,3251\n3\n\n16\n',
 '\n68\nUAE\n1,067,030\n\n2,349                                \n\n1,054,525\n\n10,156\n\n105,837\n233\n200,732,262\n19,910,389\n10,081,785 \nAsia\n\n94,2920\n\n\n1,007\n',
 '\n69\nEcuador\n1,062,275\n\n36,019                                \n\n1,025,081\n\n1,175\n759\n58,646\n1,989\n3,082,403\n170,173\n18,113,361 \nSouth America\n\n175036\n\n\n65\n',
 '\n70\nPanama\n1,040,230\n\n8,624                                \n\n1,030,855\n\n751\n16\n233,919\n1,939\n7,697,189\n1,730,886\n4,446,964 \nNorth America\n\n45161\n\n\n169\n',
 '\n71\nUruguay\n1,038,774\n\n7,634                                \n\n1,030,944\n\n196\n18\n297,131\n2,184\n6,114,822\n1,749,083\n3,496,016 \nSouth America\n\n34581\n\n\n56\n',
 '\n72\nMongolia\n1,008,655\n\n2,179                                \n\n1,006,086\n+227\n390\n192\n298,588\n645\n4,030,048\n1,193,000\n3,378,078 \nAsia\n\n31,5501\n\n\n115\n',
 '\n73\nNepal\n1,003,340\n+3\n12,031                                \n\n991,287\n+4\n22\n\n33,195\n398\n6,045,812\n200,023\n30,225,582 \nAsia\n\n302,5125\n0.10\n\n0.7\n',
 '\n74\nBelarus\n994,037\n\n7,118                                \n\n985,592\n\n1,327\n\n105,381\n755\n13,646,641\n1,446,722\n9,432,800 \nEurope\n\n91,3251\n\n\n141\n',
 '\n75\nLatvia\n977,891\n\n6,344                                \n\n971,406\n\n141\n13\n528,922\n3,431\n7,875,835\n4,259,886\n1,848,837 \nEurope\n\n22910\n\n\n76\n',
 '\n76\nSaudi Arabia\n841,469\n\n9,646                                \n\n827,923\n\n3,900\n66\n23,475\n269\n45,481,735\n1,268,848\n35,844,909 \nAsia\n\n433,7161\n\n\n109\n',
 '\n77\nAzerbaijan\n831,849\n+15\n10,274                                \n\n821,516\n+16\n59\n\n80,760\n997\n7,623,270\n740,109\n10,300,205 \nAsia\n\n121,0031\n1\n\n6\n',
 '\n78\nParaguay\n810,581\n\n19,931                                \n\nN/A\nN/A\nN/A\n7\n110,950\n2,728\n2,657,506\n363,751\n7,305,843 \nSouth America\n\n93673\n\n\n12,638\n',
 '\n79\nBahrain\n721,923\n+32\n1,564                                \n\n720,141\n+32\n218\n2\n404,669\n877\n10,855,063\n6,084,735\n1,783,983 \nAsia\n\n21,1410\n18\n\n122\n',
 '\n80\nSri Lanka\n672,467\n+8\n16,873                                \n+1\n655,556\n+15\n38\n\n31,168\n782\n6,486,117\n300,619\n21,575,842 \nAsia\n\n321,2793\n0.4\n0.05\n2\n',
 '\n81\nKuwait\n665,931\n\n2,570                                \n\n660,237\n\n3,124\n\n152,028\n587\n8,455,743\n1,930,391\n4,380,326 \nAsia\n\n71,7041\n\n\n713\n',
 '\n82\nDominican Republic\n661,176\n\n4,384                                \n\n644,785\n\n12,007\n4\n59,800\n397\n3,740,928\n338,350\n11,056,370 \nNorth America\n\n172,5223\n\n\n1,086\n',
 '\n83\nCyprus\n660,854\n\n1,364                                \n\n659,490\n\n0\n60\n540,184\n1,115\n9,640,118\n7,879,860\n1,223,387 \nAsia\n\n28970\n\n\n\n',
 '\n84\nMyanmar\n638,980\n+91\n19,494                                \n\n617,981\n+89\n1,505\n\n11,570\n353\n10,657,186\n192,970\n55,227,143 \nAsia\n\n862,8335\n2\n\n27\n',
 '\n85\nPalestine\n621,008\n\n5,404                                \n\n615,445\n\n159\n17\n116,173\n1,011\n3,078,533\n575,907\n5,345,541 \nAsia\n\n99892\n\n\n30\n',
 '\n86\nMoldova\n620,574\n\n12,118                                \n\n504,142\n\n104,314\n49\n154,634\n3,020\n3,216,305\n801,437\n4,013,171 \nEurope\n\n63311\n\n\n25,993\n',
 '\n87\nEstonia\n618,931\n\n3,001                                \n\n524,990\n\n90,940\n2\n468,210\n2,270\n3,716,945\n2,811,799\n1,321,910 \nEurope\n\n24400\n\n\n68,794\n',
 '\n88\nVenezuela\n552,695\n\n5,856                                \n\n546,537\n\n302\n31\n18,885\n200\n3,359,014\n114,771\n29,266,991 \nSouth America\n\n534,9989\n\n\n10\n',
 '\n89\nEgypt\n516,023\n\n24,613                                \n\n442,182\n\n49,228\n122\n4,861\n232\n3,693,367\n34,792\n106,156,692 \nAfrica\n\n2064,31329\n\n\n464\n',
 '\n90\nQatar\n513,500\n\n690                                \n\n512,402\n\n408\n30\n172,320\n232\n4,065,369\n1,364,257\n2,979,915 \nAsia\n\n64,3191\n\n\n137\n',
 '\n91\nLibya\n507,263\n\n6,437                                \n\n500,825\n\n1\n\n72,047\n914\n2,483,848\n352,782\n7,040,745 \nAfrica\n\n141,0943\n\n\n0.1\n',
 '\n92\nEthiopia\n500,902\n+3\n7,574                                \n\n488,131\n+1\n5,197\n1\n4,146\n63\n5,553,439\n45,967\n120,812,698 \nAfrica\n\n24115,95122\n0.02\n\n43\n',
 '\n93\nRéunion\n486,588\n\n921                                \n\n418,572\n\n67,095\n10\n535,854\n1,014\n1,603,660\n1,766,027\n908,061 \nAfrica\n\n29861\n\n\n73,888\n',
 '\n94\nHonduras\n472,619\n\n11,116                                \n\nN/A\nN/A\nN/A\n105\n46,239\n1,088\n1,660,662\n162,472\n10,221,247 \nNorth America\n\n229206\n\n\n32,184\n',
 '\n95\nArmenia\n449,203\n\n8,750                                \n\n435,162\n\n5,291\n\n151,147\n2,944\n3,242,901\n1,091,164\n2,971,966 \nAsia\n\n73401\n\n\n1,780\n',
 '\n96\nBosnia and Herzegovina\n402,998\n\n16,347                                \n\n379,084\n\n7,567\n\n124,025\n5,031\n1,884,721\n580,036\n3,249,317 \nEurope\n\n81992\n\n\n2,329\n',
 '\n97\nOman\n399,449\n\n4,628                                \n\n384,669\n\n10,152\n2\n75,028\n869\n25,000,000\n4,695,724\n5,323,993 \nAsia\n\n131,1500\n\n\n1,907\n',
 '\n98\nNorth Macedonia\n348,281\n\n9,677                                \n\n337,068\n\n1,536\n\n167,338\n4,649\n2,226,216\n1,069,626\n2,081,304 \nEurope\n\n62151\n\n\n738\n',
 '\n99\nZambia\n343,995\n\n4,058                                \n\n339,858\n\n79\n\n17,668\n208\n4,047,915\n207,903\n19,470,234 \nAfrica\n\n574,7985\n\n\n4\n',
 '\n100\nKenya\n343,074\n\n5,688                                \n\n337,309\n\n77\n1\n6,103\n101\n3,967,062\n70,569\n56,215,221 \nAfrica\n\n1649,88314\n\n\n1\n',
 '\n101\nAlbania\n334,726\n\n3,602                                \n\n329,428\n\n1,696\n\n116,777\n1,257\n1,941,032\n677,173\n2,866,374 \nEurope\n\n97961\n\n\n592\n',
 '\n102\nBotswana\n329,905\n\n2,801                                \n\n327,049\n\n55\n1\n135,143\n1,147\n2,026,898\n830,300\n2,441,162 \nAfrica\n\n78721\n\n\n23\n',
 '\n103\nLuxembourg\n319,959\n\n1,232                                \n\n316,690\n\n2,037\n\n498,091\n1,918\n4,587,145\n7,140,959\n642,371 \nEurope\n\n25210\n\n\n3,171\n',
 '\n104\nBrunei \n306,333\n\n225                                \n\n243,601\n\n62,507\n3\n687,723\n505\n717,784\n1,611,437\n445,431 \nAsia\n\n11,9801\n\n\n140,329\n',

In [7]:
data = []
for tag in tags:
    data.append(tag.text.split('\n'))
    
data

[['',
  '#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop',
  ''],
 ['',
  '',
  '',
  'North America',
  '',
  '126,752,183',
  '+4,116',
  '1,633,966',
  '+29',
  '122,650,408',
  '+8,656',
  '2,467,809',
  '6,199',
  '',
  '',
  '',
  '',
  '',
  'North America',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Asia',
  '',
  '217,623,290',
  '+28,413',
  '1,546,687',
  '+24',
  '201,245,559',
  '+19,969',
  '14,831,044',
  '15,334',
  '',
  '',
  '',
  '',
  '',
  'Asia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Europe',
  '',
  '249,411,422',
  '+4,784',
  '2,061,621',
  '+17',
  '245,413,020',
  '+16,689',
  '1,936,781',
  '5,731',
  '',
  '',
  '',
  '',
  '',
  'Europe',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'South America',
  '',
  '68,738,704',
  '+1,494',
  '1,356,298',
  '+17',
  '66,474,004',
  '+830',
  '908,402',
  '10,113',
  '',
  '',
  '',
  '',
  '',
  'South America',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Oceania',
  '',
  '14,378,181',
  '+1',
  '28,093',
  '',
  '14,200,923',
  '+1',
  '149,165',
  '99',
  '',
  '',
  '',
  '',
  '',
  'Australia/Oceania',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Africa',
  '',
  '12,823,876',
  '+6',
  '258,777',
  '',
  '12,085,577',
  '+3',
  '479,522',
  '548',
  '',
  '',
  '',
  '',
  '',
  'Africa',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  '',
  '',
  '721',
  '',
  '15',
  '',
  '706',
  '',
  '0',
  '0',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'World',
  '689,728,377',
  '+38,814',
  '6,885,457',
  '+87',
  '662,070,197',
  '+46,148',
  '20,772,723',
  '38,024',
  '88,486',
  '883.3',
  '',
  '',
  '',
  'All',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '1',
  'USA',
  '107,123,546',
  '+2,970',
  '1,165,531                                ',
  '+20',
  '105,213,261',
  '+7,455',
  '744,754',
  '1,033',
  '319,958',
  '3,481',
  '1,180,371,249',
  '3,525,546',
  '334,805,269 ',
  'North America',
  '',
  '32870',
  '9',
  '0.06',
  '2,224',
  ''],
 ['',
  '2',
  'India',
  '44,990,876',
  '',
  '531,872                                ',
  '',
  '44,455,079',
  '',
  '3,925',
  'N/A',
  '31,985',
  '378',
  '930,414,363',
  '661,448',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6452',
  '',
  '',
  '3',
  ''],
 ['',
  '3',
  'France',
  '40,090,330',
  '+3,735',
  '167,311                                ',
  '',
  '39,871,393',
  '+9,003',
  '51,626',
  '869',
  '611,277',
  '2,551',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '23920',
  '57',
  '',
  '787',
  ''],
 ['',
  '4',
  'Germany',
  '38,428,043',
  '',
  '174,323                                ',
  '',
  '38,239,600',
  '',
  '14,120',
  'N/A',
  '458,112',
  '2,078',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '24811',
  '',
  '',
  '168',
  ''],
 ['',
  '5',
  'Brazil',
  '37,601,257',
  '',
  '702,907                                ',
  '',
  '36,249,161',
  '',
  '649,189',
  'N/A',
  '174,602',
  '3,264',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63063',
  '',
  '',
  '3,015',
  ''],
 ['',
  '6',
  'Japan',
  '33,803,572',
  '',
  '74,694                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '83',
  '269,169',
  '595',
  '100,414,883',
  '799,578',
  '125,584,838 ',
  'Asia',
  '',
  '41,6811',
  '',
  '',
  '95,582',
  ''],
 ['',
  '7',
  'S. Korea',
  '31,728,115',
  '+24,604',
  '34,804                                ',
  '+20',
  '31,373,318',
  '+17,386',
  '319,993',
  '166',
  '618,122',
  '678',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '21,4753',
  '479',
  '0.4',
  '6,234',
  ''],
 ['',
  '8',
  'Italy',
  '25,857,572',
  '',
  '190,392                                ',
  '',
  '25,545,397',
  '',
  '121,783',
  '75',
  '429,080',
  '3,159',
  '272,596,017',
  '4,523,456',
  '60,262,770 ',
  'Europe',
  '',
  '23170',
  '',
  '',
  '2,021',
  ''],
 ['',
  '9',
  'UK',
  '24,603,076',
  '',
  '225,324                                ',
  '',
  '24,370,933',
  '+1,597',
  '6,819',
  'N/A',
  '359,180',
  '3,290',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '33040',
  '',
  '',
  '100',
  ''],
 ['',
  '10',
  'Russia',
  '22,929,149',
  '',
  '399,057                                ',
  '',
  '22,361,277',
  '',
  '168,815',
  'N/A',
  '157,258',
  '2,737',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '63651',
  '',
  '',
  '1,158',
  ''],
 ['',
  '11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58371',
  '',
  '',
  '4,024',
  ''],
 ['',
  '12',
  'Spain',
  '13,868,227',
  '',
  '121,213                                ',
  '',
  '13,697,426',
  '',
  '49,588',
  '231',
  '296,843',
  '2,595',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33850',
  '',
  '',
  '1,061',
  ''],
 ['',
  '13',
  'Vietnam',
  '11,613,559',
  '+951',
  '43,206                                ',
  '',
  '10,638,370',
  '+202',
  '931,983',
  '42',
  '117,364',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2901',
  '10',
  '',
  '9,418',
  ''],
 ['',
  '14',
  'Australia',
  '11,585,286',
  '',
  '20,879                                ',
  '',
  '11,526,959',
  '',
  '37,448',
  '71',
  '444,412',
  '801',
  '81,916,639',
  '3,142,326',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,2490',
  '',
  '',
  '1,437',
  ''],
 ['',
  '15',
  'Taiwan',
  '10,239,998',
  '',
  '19,005                                ',
  '',
  '10,220,993',
  '',
  '0',
  '',
  '428,656',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia',
  '',
  '21,2571',
  '',
  '',
  '',
  ''],
 ['',
  '16',
  'Argentina',
  '10,054,251',
  '',
  '130,509                                ',
  '',
  '9,923,097',
  '',
  '645',
  '363',
  '218,522',
  '2,837',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53531',
  '',
  '',
  '14',
  ''],
 ['',
  '17',
  'Netherlands',
  '8,610,372',
  '',
  '22,992                                ',
  '',
  '8,587,380',
  '',
  '0',
  '53',
  '500,270',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  '',
  ''],
 ['',
  '18',
  'Mexico',
  '7,621,062',
  '+899',
  '334,167                                ',
  '+9',
  '6,869,584',
  '+1,086',
  '417,311',
  'N/A',
  '57,927',
  '2,540',
  '20,013,810',
  '152,124',
  '131,562,772 ',
  'North America',
  '',
  '173947',
  '7',
  '0.07',
  '3,172',
  ''],
 ['',
  '19',
  'Iran',
  '7,611,743',
  '',
  '146,257                                ',
  '',
  '7,366,014',
  '',
  '99,472',
  '137',
  '88,485',
  '1,700',
  '56,669,149',
  '658,769',
  '86,022,837 ',
  'Asia',
  '',
  '115882',
  '',
  '',
  '1,156',
  ''],
 ['',
  '20',
  'Indonesia',
  '6,807,878',
  '+365',
  '161,773                                ',
  '+2',
  '6,633,617',
  '+325',
  '12,488',
  'N/A',
  '24,389',
  '580',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '411,7252',
  '1',
  '0.01',
  '45',
  ''],
 ['',
  '21',
  'Poland',
  '6,517,003',
  '+88',
  '119,615                                ',
  '+5',
  '5,335,940',
  '',
  '1,061,448',
  '185',
  '172,683',
  '3,169',
  '38,742,389',
  '1,026,566',
  '37,739,785 ',
  'Europe',
  '',
  '63161',
  '2',
  '0.1',
  '28,125',
  ''],
 ['',
  '22',
  'Colombia',
  '6,368,934',
  '+1,334',
  '142,765                                ',
  '+17',
  '6,189,718',
  '+751',
  '36,451',
  '342',
  '123,638',
  '2,771',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83611',
  '26',
  '0.3',
  '708',
  ''],
 ['',
  '23',
  'Austria',
  '6,077,443',
  '+290',
  '22,507                                ',
  '',
  '6,049,453',
  '+171',
  '5,483',
  '14',
  '670,303',
  '2,482',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe',
  '',
  '14030',
  '32',
  '',
  '605',
  ''],
 ['',
  '24',
  'Greece',
  '6,067,218',
  '',
  '36,969                                ',
  '',
  '6,016,247',
  '+4,324',
  '14,002',
  '115',
  '588,100',
  '3,583',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22790',
  '',
  '',
  '1,357',
  ''],
 ['',
  '25',
  'Portugal',
  '5,588,310',
  '',
  '26,759                                ',
  '',
  '5,556,228',
  '',
  '5,323',
  '61',
  '551,084',
  '2,639',
  '46,139,518',
  '4,549,993',
  '10,140,570 ',
  'Europe',
  '',
  '23790',
  '',
  '',
  '525',
  ''],
 ['',
  '26',
  'Ukraine',
  '5,553,031',
  '',
  '112,352                                ',
  '',
  '5,432,654',
  '',
  '8,025',
  '',
  '128,566',
  '2,601',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83841',
  '',
  '',
  '186',
  ''],
 ['',
  '27',
  'Chile',
  '5,287,504',
  '+60',
  '64,497                                ',
  '',
  '5,222,878',
  '+36',
  '129',
  '23',
  '274,673',
  '3,350',
  '49,680,986',
  '2,580,804',
  '19,250,195 ',
  'South America',
  '',
  '42980',
  '3',
  '',
  '7',
  ''],
 ['',
  '28',
  'Malaysia',
  '5,100,249',
  '',
  '37,087                                ',
  '',
  '5,044,652',
  '',
  '18,510',
  '36',
  '153,710',
  '1,118',
  '68,352,292',
  '2,059,978',
  '33,181,072 ',
  'Asia',
  '',
  '78950',
  '',
  '',
  '558',
  ''],
 ['',
  '29',
  'Israel',
  '4,826,031',
  '',
  '12,527                                ',
  '',
  '4,798,473',
  '',
  '15,031',
  '21',
  '517,481',
  '1,343',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27440',
  '',
  '',
  '1,612',
  ''],
 ['',
  '30',
  'Belgium',
  '4,799,107',
  '',
  '34,336                                ',
  '',
  '4,760,035',
  '+236',
  '4,736',
  '43',
  '411,295',
  '2,943',
  '37,018,657',
  '3,172,590',
  '11,668,278 ',
  'Europe',
  '',
  '23400',
  '',
  '',
  '406',
  ''],
 ['',
  '31',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  '',
  ''],
 ['',
  '32',
  'Thailand',
  '4,738,988',
  '',
  '34,053                                ',
  '',
  '4,692,636',
  '',
  '12,299',
  'N/A',
  '67,624',
  '486',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '',
  '152,0584',
  '',
  '',
  '176',
  ''],
 ['',
  '33',
  'Canada',
  '4,676,878',
  '',
  '52,425                                ',
  '',
  '4,588,876',
  '',
  '35,577',
  '99',
  '121,830',
  '1,366',
  '66,343,123',
  '1,728,207',
  '38,388,419 ',
  'North America',
  '',
  '87321',
  '',
  '',
  '927',
  ''],
 ['',
  '34',
  'Czechia',
  '4,642,155',
  '+38',
  '42,804                                ',
  '',
  '4,598,570',
  '+33',
  '781',
  '',
  '432,360',
  '3,987',
  '57,214,069',
  '5,328,790',
  '10,736,784 ',
  'Europe',
  '',
  '22510',
  '4',
  '',
  '73',
  ''],
 ['',
  '35',
  'Peru',
  '4,507,363',
  '',
  '220,673                                ',
  '',
  '4,284,940',
  '',
  '1,750',
  '26',
  '133,812',
  '6,551',
  '38,548,796',
  '1,144,417',
  '33,684,208 ',
  'South America',
  '',
  '71531',
  '',
  '',
  '52',
  ''],
 ['',
  '36',
  'Switzerland',
  '4,405,938',
  '',
  '14,452                                ',
  '',
  '4,389,039',
  '',
  '2,447',
  '39',
  '502,179',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe',
  '',
  '26070',
  '',
  '',
  '279',
  ''],
 ['',
  '37',
  'Philippines',
  '4,144,351',
  '+1,537',
  '66,466                                ',
  '',
  '4,062,467',
  '+957',
  '15,418',
  '162',
  '36,836',
  '591',
  '35,267,600',
  '313,465',
  '112,508,994 ',
  'Asia',
  '',
  '271,6933',
  '14',
  '',
  '137',
  ''],
 ['',
  '38',
  'South Africa',
  '4,076,463',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '1,010',
  ''],
 ['',
  '39',
  'Romania',
  '3,404,197',
  '',
  '68,184                                ',
  '',
  '3,329,181',
  '',
  '6,832',
  '78',
  '178,873',
  '3,583',
  '27,516,705',
  '1,445,863',
  '19,031,335 ',
  'Europe',
  '',
  '62791',
  '',
  '',
  '359',
  ''],
 ['',
  '40',
  'Denmark',
  '3,181,900',
  '+22',
  '8,708                                ',
  '+3',
  '3,172,759',
  '',
  '433',
  '5',
  '545,317',
  '1,492',
  '129,287,322',
  '22,157,400',
  '5,834,950 ',
  'Europe',
  '',
  '26700',
  '4',
  '0.5',
  '74',
  ''],
 ['',
  '41',
  'Hong Kong',
  '2,904,315',
  '',
  '13,819                                ',
  '',
  '2,875,092',
  '+336',
  '15,404',
  '28',
  '381,931',
  '1,817',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia',
  '',
  '35500',
  '',
  '',
  '2,026',
  ''],
 ['',
  '42',
  'Sweden',
  '2,710,457',
  '',
  '24,389                                ',
  '',
  '2,683,140',
  '+307',
  '2,928',
  '8',
  '265,238',
  '2,387',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe',
  '',
  '44191',
  '',
  '',
  '287',
  ''],
 ['',
  '43',
  'Serbia',
  '2,542,012',
  '+309',
  '18,053                                ',
  '+1',
  '2,520,603',
  '+110',
  '3,356',
  '6',
  '293,772',
  '2,086',
  '12,939,760',
  '1,495,405',
  '8,653,016 ',
  'Europe',
  '',
  '34791',
  '36',
  '0.1',
  '388',
  ''],
 ['',
  '44',
  'Singapore',
  '2,472,873',
  '',
  '1,727                                ',
  '',
  '2,149,583',
  '',
  '321,563',
  '2',
  '416,060',
  '291',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia',
  '',
  '23,4420',
  '',
  '',
  '54,103',
  ''],
 ['',
  '45',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16',
  ''],
 ['',
  '46',
  'New Zealand',
  '2,375,191',
  '',
  '4,362                                ',
  '',
  '2,358,376',
  '',
  '12,453',
  '',
  '484,911',
  '891',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '21,1231',
  '',
  '',
  '2,542',
  ''],
 ['',
  '47',
  'Hungary',
  '2,202,887',
  '+171',
  '48,873                                ',
  '+5',
  '2,151,825',
  '+526',
  '2,189',
  '2',
  '229,318',
  '5,088',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41971',
  '18',
  '0.5',
  '228',
  ''],
 ['',
  '48',
  'Bangladesh',
  '2,039,244',
  '',
  '29,446                                ',
  '',
  '1,998,448',
  '',
  '11,350',
  'N/A',
  '12,147',
  '175',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia',
  '',
  '825,70111',
  '',
  '',
  '68',
  ''],
 ['',
  '49',
  'Slovakia',
  '1,866,857',
  '',
  '21,167                                ',
  '',
  '1,845,578',
  '',
  '112',
  '11',
  '341,903',
  '3,877',
  '7,432,749',
  '1,361,261',
  '5,460,193 ',
  'Europe',
  '',
  '32581',
  '',
  '',
  '21',
  ''],
 ['',
  '50',
  'Georgia',
  '1,842,046',
  '',
  '17,070                                ',
  '',
  '1,776,548',
  '',
  '48,428',
  '',
  '464,139',
  '4,301',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22320',
  '',
  '',
  '12,202',
  ''],
 ['',
  '51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181',
  ''],
 ['',
  '52',
  'Ireland',
  '1,712,113',
  '',
  '8,960                                ',
  '',
  '1,701,342',
  '',
  '1,811',
  '19',
  '341,045',
  '1,785',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe',
  '',
  '35600',
  '',
  '',
  '361',
  ''],
 ['',
  '53',
  'Pakistan',
  '1,581,038',
  '+5',
  '30,660                                ',
  '',
  '1,538,689',
  '',
  '11,689',
  '7',
  '6,889',
  '134',
  '30,571,377',
  '133,215',
  '229,488,994 ',
  'Asia',
  '',
  '1457,4858',
  '0.02',
  '',
  '51',
  ''],
 ['',
  '54',
  'Norway',
  '1,484,882',
  '',
  '5,435                                ',
  '',
  '1,478,204',
  '',
  '1,243',
  '20',
  '269,422',
  '986',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '41,0141',
  '',
  '',
  '226',
  ''],
 ['',
  '55',
  'Finland',
  '1,480,370',
  '',
  '9,750                                ',
  '',
  '1,466,950',
  '+291',
  '3,670',
  '21',
  '266,495',
  '1,755',
  '12,101,220',
  '2,178,453',
  '5,554,960 ',
  'Europe',
  '',
  '45700',
  '',
  '',
  '661',
  ''],
 ['',
  '56',
  'Kazakhstan',
  '1,411,831',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '14,963',
  '24',
  '73,514',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,3872',
  '',
  '',
  '779',
  ''],
 ['',
  '57',
  'Slovenia',
  '1,344,023',
  '+19',
  '7,100                                ',
  '',
  '1,328,006',
  '',
  '8,917',
  '8',
  '646,776',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe',
  '',
  '22931',
  '9',
  '',
  '4,291',
  ''],
 ['',
  '58',
  'Lithuania',
  '1,320,534',
  '+31',
  '9,684                                ',
  '',
  '1,309,711',
  '+71',
  '1,139',
  '1',
  '496,123',
  '3,638',
  '10,453,692',
  '3,927,438',
  '2,661,708 ',
  'Europe',
  '',
  '22750',
  '12',
  '',
  '428',
  ''],
 ['',
  '59',
  'Bulgaria',
  '1,307,678',
  '+81',
  '38,388                                ',
  '+3',
  '1,267,371',
  '+84',
  '1,919',
  '31',
  '191,053',
  '5,609',
  '11,238,787',
  '1,641,994',
  '6,844,597 ',
  'Europe',
  '',
  '51781',
  '12',
  '0.4',
  '280',
  ''],
 ['',
  '60',
  'Morocco',
  '1,274,180',
  '',
  '16,297                                ',
  '',
  '1,256,151',
  '',
  '1,732',
  '3',
  '33,733',
  '431',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa',
  '',
  '302,3183',
  '',
  '',
  '46',
  ''],
 ['',
  '61',
  'Croatia',
  '1,273,795',
  '',
  '18,255                                ',
  '',
  '1,255,288',
  '',
  '252',
  '6',
  '313,798',
  '4,497',
  '5,603,151',
  '1,380,329',
  '4,059,286 ',
  'Europe',
  '',
  '32221',
  '',
  '',
  '62',
  ''],
 ['',
  '62',
  'Guatemala',
  '1,252,899',
  '+209',
  '20,201                                ',
  '',
  '1,230,457',
  '+80',
  '2,241',
  '5',
  '67,418',
  '1,087',
  '7,342,086',
  '395,075',
  '18,584,039 ',
  'North America',
  '',
  '159203',
  '11',
  '',
  '121',
  ''],
 ['',
  '63',
  'Lebanon',
  '1,237,556',
  '',
  '10,914                                ',
  '',
  '1,087,587',
  '',
  '139,055',
  '74',
  '185,128',
  '1,633',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56131',
  '',
  '',
  '20,802',
  ''],
 ['',
  '64',
  'Costa Rica',
  '1,232,576',
  '',
  '9,374                                ',
  '',
  '860,711',
  '',
  '362,491',
  '52',
  '237,841',
  '1,809',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45531',
  '',
  '',
  '69,947',
  ''],
 ['',
  '65',
  'Bolivia',
  '1,199,346',
  '+100',
  '22,384                                ',
  '',
  '1,168,509',
  '+43',
  '8,453',
  '220',
  '100,007',
  '1,866',
  '2,710,261',
  '225,993',

In [9]:
import csv
file = open('covid_data.csv', 'w')
x = csv.writer(file)
x.writerows(data)
file.close()

In [10]:
import pandas as pd
df = pd.read_csv('covid_data.csv',encoding = 'latin1')
df

                                                 Unnamed: 0            #  \
NaN NaN NaN    North America NaN     126,752,183     +4,116    1,633,966
               Asia          NaN     217,623,290    +28,413    1,546,687
               Europe        NaN     249,411,422     +4,784    2,061,621
               South America NaN     68,738,704      +1,494    1,356,298
               Oceania       NaN     14,378,181          +1       28,093
...                                                     ...          ...
        Total: 68,738,704    +1,494  1,356,298          +17   66,474,004
               14,378,181    +1      28,093             NaN   14,200,923
               12,823,876    +6      258,777            NaN   12,085,577
               721           NaN     15                 NaN          706
               689,728,377   +38,814 6,885,457          +87  662,070,197

                                                 Country,Other   TotalCases  \
NaN NaN NaN    North America NaN     126,752,183           +29  122,650,408
               Asia          NaN     217,623,290           +24  201,245,559
               Europe        NaN     249,411,422           +17  245,413,020
               South America NaN     68,738,704            +17   66,474,004
               Oceania       NaN     14,378,181            NaN   14,200,923
...                                                        ...          ...
        Total: 68,738,704    +1,494  1,356,298            +830      908,402
               14,378,181    +1      28,093                NaN      149,165
               12,823,876    +6      258,777               NaN      479,522
               721           NaN     15                    NaN            0
               689,728,377   +38,814 6,885,457         +46,148   20,772,723

                                                 NewCases TotalDeaths  \
NaN NaN NaN    North America NaN     126,752,183   +8,656   2,467,809
               Asia          NaN     217,623,290  +19,969  14,831,044
               Europe        NaN     249,411,422  +16,689   1,936,781
               South America NaN     68,738,704      +830     908,402
               Oceania       NaN     14,378,181        +1     149,165
...                                                   ...         ...
        Total: 68,738,704    +1,494  1,356,298     10,113         NaN
               14,378,181    +1      28,093            99         NaN
               12,823,876    +6      258,777          548         NaN
               721           NaN     15                 0         NaN
               689,728,377   +38,814 6,885,457     38,024    88,485.7

                                                 NewDeaths TotalRecovered  \
NaN NaN NaN    North America NaN     126,752,183     6,199            NaN
               Asia          NaN     217,623,290    15,334            NaN
               Europe        NaN     249,411,422     5,731            NaN
               South America NaN     68,738,704     10,113            NaN
               Oceania       NaN     14,378,181         99            NaN
...                                                    ...            ...
        Total: 68,738,704    +1,494  1,356,298         NaN            NaN
               14,378,181    +1      28,093            NaN            NaN
               12,823,876    +6      258,777           NaN            NaN
               721           NaN     15                NaN            NaN
               689,728,377   +38,814 6,885,457       883.3            NaN

                                                 NewRecovered ActiveCases  \
NaN NaN NaN    North America NaN     126,752,183          NaN         NaN
               Asia          NaN     217,623,290          NaN         NaN
               Europe        NaN     249,411,422          NaN         NaN
               South America NaN     68,738,704           NaN         NaN
               Oceania       NaN     14,378,181           NaN         NaN
...                                                       ...         ...
        Total: 68,738,704    +1,494  1,356,298            NaN         NaN
               14,378,181    +1      28,093               NaN         NaN
               12,823,876    +6      258,777              NaN         NaN
               721           NaN     15                   NaN         NaN
               689,728,377   +38,814 6,885,457            NaN         NaN

                                                  ... Tests/  1M pop  \
NaN NaN NaN    North America NaN     126,752,183  ...    NaN     NaN
               Asia          NaN     217,623,290  ...    NaN     NaN
               Europe        NaN     249,411,422  ...    NaN     NaN
               South America NaN     68,738,704   ...    NaN     NaN
               Oceania       NaN     14,378,181   ...    NaN     NaN
...                                               ...    ...     ...
        Total: 68,738,704    +1,494  1,356,298    ...    NaN     NaN
               14,378,181    +1      28,093       ...    NaN     NaN
               12,823,876    +6      258,777      ...    NaN     NaN
               721           NaN     15           ...    NaN     NaN
               689,728,377   +38,814 6,885,457    ...    NaN     NaN

                                                 Unnamed: 16 Population  \
NaN NaN NaN    North America NaN     126,752,183         NaN        NaN
               Asia          NaN     217,623,290         NaN        NaN
               Europe        NaN     249,411,422         NaN        NaN
               South America NaN     68,738,704          NaN        NaN
               Oceania       NaN     14,378,181          NaN        NaN
...                                                      ...        ...
        Total: 68,738,704    +1,494  1,356,298           NaN        NaN
               14,378,181    +1      28,093              NaN        NaN
               12,823,876    +6      258,777             NaN        NaN
               721           NaN     15                  NaN        NaN
               689,728,377   +38,814 6,885,457           NaN        NaN

                                                  Continent  \
NaN NaN NaN    North America NaN     126,752,183        NaN
               Asia          NaN     217,623,290        NaN
               Europe        NaN     249,411,422        NaN
               South America NaN     68,738,704         NaN
               Oceania       NaN     14,378,181         NaN
...                                                     ...
        Total: 68,738,704    +1,494  1,356,298          NaN
               14,378,181    +1      28,093             NaN
               12,823,876    +6      258,777            NaN
               721           NaN     15                 NaN
               689,728,377   +38,814 6,885,457          NaN

                                                 1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl  \
NaN NaN NaN    North America NaN     126,752,183                                                NaN
               Asia          NaN     217,623,290                                                NaN
               Europe        NaN     249,411,422                                                NaN
               South America NaN     68,738,704                                                 NaN
               Oceania       NaN     14,378,181                                                 NaN
...                                                                                             ...
        Total: 68,738,704    +1,494  1,356,298                                                  NaN
               14,378,181    +1      28,093                                                     NaN
               12,823,876    +6      258,777                                                    NaN
               721           NaN     15                                                         NaN
               689,728,377   +38,814 6,885,457                                                  NaN

                                                  New Cases/1M pop  \
NaN NaN NaN    North America NaN     126,752,183               NaN
               Asia          NaN     217,623,290               NaN
               Europe        NaN     249,411,422               NaN
               South America NaN     68,738,704                NaN
               Oceania       NaN     14,378,181                NaN
...                                                            ...
        Total: 68,738,704    +1,494  1,356,298                 NaN
               14,378,181    +1      28,093                    NaN
               12,823,876    +6      258,777                   NaN
               721           NaN     15                        NaN
               689,728,377   +38,814 6,885,457                 NaN

                                                  New Deaths/1M pop  \
NaN NaN NaN    North America NaN     126,752,183                NaN
               Asia          NaN     217,623,290                NaN
               Europe        NaN     249,411,422                NaN
               South America NaN     68,738,704                 NaN
               Oceania       NaN     14,378,181                 NaN
...                                                             ...
        Total: 68,738,704    +1,494  1,356,298                  NaN
               14,378,181    +1      28,093                     NaN
               12,823,876    +6      258,777                    NaN
               721           NaN     15                         NaN
               689,728,377   +38,814 6,885,457                  NaN

                                                  Active Cases/1M pop  \
NaN NaN NaN    North America NaN     126,752,183                  NaN
               Asia          NaN     217,623,290                  NaN
               Europe        NaN     249,411,422                  NaN
               South America NaN     68,738,704                   NaN
               Oceania       NaN     14,378,181                   NaN
...                                                               ...
        Total: 68,738,704    +1,494  1,356,298                    NaN
               14,378,181    +1      28,093                       NaN
               12,823,876    +6      258,777                      NaN
               721           NaN     15                           NaN
               689,728,377   +38,814 6,885,457                    NaN

                                                  Unnamed: 23
NaN NaN NaN    North America NaN     126,752,183          NaN
               Asia          NaN     217,623,290          NaN
               Europe        NaN     249,411,422          NaN
               South America NaN     68,738,704           NaN
               Oceania       NaN     14,378,181           NaN
...                                                       ...
        Total: 68,738,704    +1,494  1,356,298            NaN
               14,378,181    +1      28,093               NaN
               12,823,876    +6      258,777              NaN
               721           NaN     15                   NaN
               689,728,377   +38,814 6,885,457            NaN

[247 rows x 24 columns]

In [13]:
data = []
for tag in tags:
    y = tag.text.split('\n')
    if y[1] !="":
        data.append(y)
data

[['',
  '#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop',
  ''],
 ['',
  '1',
  'USA',
  '107,123,546',
  '+2,970',
  '1,165,531                                ',
  '+20',
  '105,213,261',
  '+7,455',
  '744,754',
  '1,033',
  '319,958',
  '3,481',
  '1,180,371,249',
  '3,525,546',
  '334,805,269 ',
  'North America',
  '',
  '32870',
  '9',
  '0.06',
  '2,224',
  ''],
 ['',
  '2',
  'India',
  '44,990,876',
  '',
  '531,872                                ',
  '',
  '44,455,079',
  '',
  '3,925',
  'N/A',
  '31,985',
  '378',
  '930,414,363',
  '661,448',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6452',
  '',
  '',
  '3',
  ''],
 ['',
  '3',
  'France',
  '40,090,330',
  '+3,735',
  '167,311                                ',
  '',
  '39,871,393',
  '+9,003',
  '51,626',
  '869',
  '611,277',
  '2,551',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '23920',
  '57',
  '',
  '787',
  ''],
 ['',
  '4',
  'Germany',
  '38,428,043',
  '',
  '174,323                                ',
  '',
  '38,239,600',
  '',
  '14,120',
  'N/A',
  '458,112',
  '2,078',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '24811',
  '',
  '',
  '168',
  ''],
 ['',
  '5',
  'Brazil',
  '37,601,257',
  '',
  '702,907                                ',
  '',
  '36,249,161',
  '',
  '649,189',
  'N/A',
  '174,602',
  '3,264',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63063',
  '',
  '',
  '3,015',
  ''],
 ['',
  '6',
  'Japan',
  '33,803,572',
  '',
  '74,694                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '83',
  '269,169',
  '595',
  '100,414,883',
  '799,578',
  '125,584,838 ',
  'Asia',
  '',
  '41,6811',
  '',
  '',
  '95,582',
  ''],
 ['',
  '7',
  'S. Korea',
  '31,728,115',
  '+24,604',
  '34,804                                ',
  '+20',
  '31,373,318',
  '+17,386',
  '319,993',
  '166',
  '618,122',
  '678',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '21,4753',
  '479',
  '0.4',
  '6,234',
  ''],
 ['',
  '8',
  'Italy',
  '25,857,572',
  '',
  '190,392                                ',
  '',
  '25,545,397',
  '',
  '121,783',
  '75',
  '429,080',
  '3,159',
  '272,596,017',
  '4,523,456',
  '60,262,770 ',
  'Europe',
  '',
  '23170',
  '',
  '',
  '2,021',
  ''],
 ['',
  '9',
  'UK',
  '24,603,076',
  '',
  '225,324                                ',
  '',
  '24,370,933',
  '+1,597',
  '6,819',
  'N/A',
  '359,180',
  '3,290',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '33040',
  '',
  '',
  '100',
  ''],
 ['',
  '10',
  'Russia',
  '22,929,149',
  '',
  '399,057                                ',
  '',
  '22,361,277',
  '',
  '168,815',
  'N/A',
  '157,258',
  '2,737',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '63651',
  '',
  '',
  '1,158',
  ''],
 ['',
  '11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58371',
  '',
  '',
  '4,024',
  ''],
 ['',
  '12',
  'Spain',
  '13,868,227',
  '',
  '121,213                                ',
  '',
  '13,697,426',
  '',
  '49,588',
  '231',
  '296,843',
  '2,595',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33850',
  '',
  '',
  '1,061',
  ''],
 ['',
  '13',
  'Vietnam',
  '11,613,559',
  '+951',
  '43,206                                ',
  '',
  '10,638,370',
  '+202',
  '931,983',
  '42',
  '117,364',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2901',
  '10',
  '',
  '9,418',
  ''],
 ['',
  '14',
  'Australia',
  '11,585,286',
  '',
  '20,879                                ',
  '',
  '11,526,959',
  '',
  '37,448',
  '71',
  '444,412',
  '801',
  '81,916,639',
  '3,142,326',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,2490',
  '',
  '',
  '1,437',
  ''],
 ['',
  '15',
  'Taiwan',
  '10,239,998',
  '',
  '19,005                                ',
  '',
  '10,220,993',
  '',
  '0',
  '',
  '428,656',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia',
  '',
  '21,2571',
  '',
  '',
  '',
  ''],
 ['',
  '16',
  'Argentina',
  '10,054,251',
  '',
  '130,509                                ',
  '',
  '9,923,097',
  '',
  '645',
  '363',
  '218,522',
  '2,837',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53531',
  '',
  '',
  '14',
  ''],
 ['',
  '17',
  'Netherlands',
  '8,610,372',
  '',
  '22,992                                ',
  '',
  '8,587,380',
  '',
  '0',
  '53',
  '500,270',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  '',
  ''],
 ['',
  '18',
  'Mexico',
  '7,621,062',
  '+899',
  '334,167                                ',
  '+9',
  '6,869,584',
  '+1,086',
  '417,311',
  'N/A',
  '57,927',
  '2,540',
  '20,013,810',
  '152,124',
  '131,562,772 ',
  'North America',
  '',
  '173947',
  '7',
  '0.07',
  '3,172',
  ''],
 ['',
  '19',
  'Iran',
  '7,611,743',
  '',
  '146,257                                ',
  '',
  '7,366,014',
  '',
  '99,472',
  '137',
  '88,485',
  '1,700',
  '56,669,149',
  '658,769',
  '86,022,837 ',
  'Asia',
  '',
  '115882',
  '',
  '',
  '1,156',
  ''],
 ['',
  '20',
  'Indonesia',
  '6,807,878',
  '+365',
  '161,773                                ',
  '+2',
  '6,633,617',
  '+325',
  '12,488',
  'N/A',
  '24,389',
  '580',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '411,7252',
  '1',
  '0.01',
  '45',
  ''],
 ['',
  '21',
  'Poland',
  '6,517,003',
  '+88',
  '119,615                                ',
  '+5',
  '5,335,940',
  '',
  '1,061,448',
  '185',
  '172,683',
  '3,169',
  '38,742,389',
  '1,026,566',
  '37,739,785 ',
  'Europe',
  '',
  '63161',
  '2',
  '0.1',
  '28,125',
  ''],
 ['',
  '22',
  'Colombia',
  '6,368,934',
  '+1,334',
  '142,765                                ',
  '+17',
  '6,189,718',
  '+751',
  '36,451',
  '342',
  '123,638',
  '2,771',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83611',
  '26',
  '0.3',
  '708',
  ''],
 ['',
  '23',
  'Austria',
  '6,077,443',
  '+290',
  '22,507                                ',
  '',
  '6,049,453',
  '+171',
  '5,483',
  '14',
  '670,303',
  '2,482',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe',
  '',
  '14030',
  '32',
  '',
  '605',
  ''],
 ['',
  '24',
  'Greece',
  '6,067,218',
  '',
  '36,969                                ',
  '',
  '6,016,247',
  '+4,324',
  '14,002',
  '115',
  '588,100',
  '3,583',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22790',
  '',
  '',
  '1,357',
  ''],
 ['',
  '25',
  'Portugal',
  '5,588,310',
  '',
  '26,759                                ',
  '',
  '5,556,228',
  '',
  '5,323',
  '61',
  '551,084',
  '2,639',
  '46,139,518',
  '4,549,993',
  '10,140,570 ',
  'Europe',
  '',
  '23790',
  '',
  '',
  '525',
  ''],
 ['',
  '26',
  'Ukraine',
  '5,553,031',
  '',
  '112,352                                ',
  '',
  '5,432,654',
  '',
  '8,025',
  '',
  '128,566',
  '2,601',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83841',
  '',
  '',
  '186',
  ''],
 ['',
  '27',
  'Chile',
  '5,287,504',
  '+60',
  '64,497                                ',
  '',
  '5,222,878',
  '+36',
  '129',
  '23',
  '274,673',
  '3,350',
  '49,680,986',
  '2,580,804',
  '19,250,195 ',
  'South America',
  '',
  '42980',
  '3',
  '',
  '7',
  ''],
 ['',
  '28',
  'Malaysia',
  '5,100,249',
  '',
  '37,087                                ',
  '',
  '5,044,652',
  '',
  '18,510',
  '36',
  '153,710',
  '1,118',
  '68,352,292',
  '2,059,978',
  '33,181,072 ',
  'Asia',
  '',
  '78950',
  '',
  '',
  '558',
  ''],
 ['',
  '29',
  'Israel',
  '4,826,031',
  '',
  '12,527                                ',
  '',
  '4,798,473',
  '',
  '15,031',
  '21',
  '517,481',
  '1,343',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27440',
  '',
  '',
  '1,612',
  ''],
 ['',
  '30',
  'Belgium',
  '4,799,107',
  '',
  '34,336                                ',
  '',
  '4,760,035',
  '+236',
  '4,736',
  '43',
  '411,295',
  '2,943',
  '37,018,657',
  '3,172,590',
  '11,668,278 ',
  'Europe',
  '',
  '23400',
  '',
  '',
  '406',
  ''],
 ['',
  '31',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  '',
  ''],
 ['',
  '32',
  'Thailand',
  '4,738,988',
  '',
  '34,053                                ',
  '',
  '4,692,636',
  '',
  '12,299',
  'N/A',
  '67,624',
  '486',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '',
  '152,0584',
  '',
  '',
  '176',
  ''],
 ['',
  '33',
  'Canada',
  '4,676,878',
  '',
  '52,425                                ',
  '',
  '4,588,876',
  '',
  '35,577',
  '99',
  '121,830',
  '1,366',
  '66,343,123',
  '1,728,207',
  '38,388,419 ',
  'North America',
  '',
  '87321',
  '',
  '',
  '927',
  ''],
 ['',
  '34',
  'Czechia',
  '4,642,155',
  '+38',
  '42,804                                ',
  '',
  '4,598,570',
  '+33',
  '781',
  '',
  '432,360',
  '3,987',
  '57,214,069',
  '5,328,790',
  '10,736,784 ',
  'Europe',
  '',
  '22510',
  '4',
  '',
  '73',
  ''],
 ['',
  '35',
  'Peru',
  '4,507,363',
  '',
  '220,673                                ',
  '',
  '4,284,940',
  '',
  '1,750',
  '26',
  '133,812',
  '6,551',
  '38,548,796',
  '1,144,417',
  '33,684,208 ',
  'South America',
  '',
  '71531',
  '',
  '',
  '52',
  ''],
 ['',
  '36',
  'Switzerland',
  '4,405,938',
  '',
  '14,452                                ',
  '',
  '4,389,039',
  '',
  '2,447',
  '39',
  '502,179',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe',
  '',
  '26070',
  '',
  '',
  '279',
  ''],
 ['',
  '37',
  'Philippines',
  '4,144,351',
  '+1,537',
  '66,466                                ',
  '',
  '4,062,467',
  '+957',
  '15,418',
  '162',
  '36,836',
  '591',
  '35,267,600',
  '313,465',
  '112,508,994 ',
  'Asia',
  '',
  '271,6933',
  '14',
  '',
  '137',
  ''],
 ['',
  '38',
  'South Africa',
  '4,076,463',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '1,010',
  ''],
 ['',
  '39',
  'Romania',
  '3,404,197',
  '',
  '68,184                                ',
  '',
  '3,329,181',
  '',
  '6,832',
  '78',
  '178,873',
  '3,583',
  '27,516,705',
  '1,445,863',
  '19,031,335 ',
  'Europe',
  '',
  '62791',
  '',
  '',
  '359',
  ''],
 ['',
  '40',
  'Denmark',
  '3,181,900',
  '+22',
  '8,708                                ',
  '+3',
  '3,172,759',
  '',
  '433',
  '5',
  '545,317',
  '1,492',
  '129,287,322',
  '22,157,400',
  '5,834,950 ',
  'Europe',
  '',
  '26700',
  '4',
  '0.5',
  '74',
  ''],
 ['',
  '41',
  'Hong Kong',
  '2,904,315',
  '',
  '13,819                                ',
  '',
  '2,875,092',
  '+336',
  '15,404',
  '28',
  '381,931',
  '1,817',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia',
  '',
  '35500',
  '',
  '',
  '2,026',
  ''],
 ['',
  '42',
  'Sweden',
  '2,710,457',
  '',
  '24,389                                ',
  '',
  '2,683,140',
  '+307',
  '2,928',
  '8',
  '265,238',
  '2,387',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe',
  '',
  '44191',
  '',
  '',
  '287',
  ''],
 ['',
  '43',
  'Serbia',
  '2,542,012',
  '+309',
  '18,053                                ',
  '+1',
  '2,520,603',
  '+110',
  '3,356',
  '6',
  '293,772',
  '2,086',
  '12,939,760',
  '1,495,405',
  '8,653,016 ',
  'Europe',
  '',
  '34791',
  '36',
  '0.1',
  '388',
  ''],
 ['',
  '44',
  'Singapore',
  '2,472,873',
  '',
  '1,727                                ',
  '',
  '2,149,583',
  '',
  '321,563',
  '2',
  '416,060',
  '291',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia',
  '',
  '23,4420',
  '',
  '',
  '54,103',
  ''],
 ['',
  '45',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16',
  ''],
 ['',
  '46',
  'New Zealand',
  '2,375,191',
  '',
  '4,362                                ',
  '',
  '2,358,376',
  '',
  '12,453',
  '',
  '484,911',
  '891',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '21,1231',
  '',
  '',
  '2,542',
  ''],
 ['',
  '47',
  'Hungary',
  '2,202,887',
  '+171',
  '48,873                                ',
  '+5',
  '2,151,825',
  '+526',
  '2,189',
  '2',
  '229,318',
  '5,088',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41971',
  '18',
  '0.5',
  '228',
  ''],
 ['',
  '48',
  'Bangladesh',
  '2,039,244',
  '',
  '29,446                                ',
  '',
  '1,998,448',
  '',
  '11,350',
  'N/A',
  '12,147',
  '175',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia',
  '',
  '825,70111',
  '',
  '',
  '68',
  ''],
 ['',
  '49',
  'Slovakia',
  '1,866,857',
  '',
  '21,167                                ',
  '',
  '1,845,578',
  '',
  '112',
  '11',
  '341,903',
  '3,877',
  '7,432,749',
  '1,361,261',
  '5,460,193 ',
  'Europe',
  '',
  '32581',
  '',
  '',
  '21',
  ''],
 ['',
  '50',
  'Georgia',
  '1,842,046',
  '',
  '17,070                                ',
  '',
  '1,776,548',
  '',
  '48,428',
  '',
  '464,139',
  '4,301',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22320',
  '',
  '',
  '12,202',
  ''],
 ['',
  '51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181',
  ''],
 ['',
  '52',
  'Ireland',
  '1,712,113',
  '',
  '8,960                                ',
  '',
  '1,701,342',
  '',
  '1,811',
  '19',
  '341,045',
  '1,785',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe',
  '',
  '35600',
  '',
  '',
  '361',
  ''],
 ['',
  '53',
  'Pakistan',
  '1,581,038',
  '+5',
  '30,660                                ',
  '',
  '1,538,689',
  '',
  '11,689',
  '7',
  '6,889',
  '134',
  '30,571,377',
  '133,215',
  '229,488,994 ',
  'Asia',
  '',
  '1457,4858',
  '0.02',
  '',
  '51',
  ''],
 ['',
  '54',
  'Norway',
  '1,484,882',
  '',
  '5,435                                ',
  '',
  '1,478,204',
  '',
  '1,243',
  '20',
  '269,422',
  '986',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '41,0141',
  '',
  '',
  '226',
  ''],
 ['',
  '55',
  'Finland',
  '1,480,370',
  '',
  '9,750                                ',
  '',
  '1,466,950',
  '+291',
  '3,670',
  '21',
  '266,495',
  '1,755',
  '12,101,220',
  '2,178,453',
  '5,554,960 ',
  'Europe',
  '',
  '45700',
  '',
  '',
  '661',
  ''],
 ['',
  '56',
  'Kazakhstan',
  '1,411,831',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '14,963',
  '24',
  '73,514',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,3872',
  '',
  '',
  '779',
  ''],
 ['',
  '57',
  'Slovenia',
  '1,344,023',
  '+19',
  '7,100                                ',
  '',
  '1,328,006',
  '',
  '8,917',
  '8',
  '646,776',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe',
  '',
  '22931',
  '9',
  '',
  '4,291',
  ''],
 ['',
  '58',
  'Lithuania',
  '1,320,534',
  '+31',
  '9,684                                ',
  '',
  '1,309,711',
  '+71',
  '1,139',
  '1',
  '496,123',
  '3,638',
  '10,453,692',
  '3,927,438',
  '2,661,708 ',
  'Europe',
  '',
  '22750',
  '12',
  '',
  '428',
  ''],
 ['',
  '59',
  'Bulgaria',
  '1,307,678',
  '+81',
  '38,388                                ',
  '+3',
  '1,267,371',
  '+84',
  '1,919',
  '31',
  '191,053',
  '5,609',
  '11,238,787',
  '1,641,994',
  '6,844,597 ',
  'Europe',
  '',
  '51781',
  '12',
  '0.4',
  '280',
  ''],
 ['',
  '60',
  'Morocco',
  '1,274,180',
  '',
  '16,297                                ',
  '',
  '1,256,151',
  '',
  '1,732',
  '3',
  '33,733',
  '431',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa',
  '',
  '302,3183',
  '',
  '',
  '46',
  ''],
 ['',
  '61',
  'Croatia',
  '1,273,795',
  '',
  '18,255                                ',
  '',
  '1,255,288',
  '',
  '252',
  '6',
  '313,798',
  '4,497',
  '5,603,151',
  '1,380,329',
  '4,059,286 ',
  'Europe',
  '',
  '32221',
  '',
  '',
  '62',
  ''],
 ['',
  '62',
  'Guatemala',
  '1,252,899',
  '+209',
  '20,201                                ',
  '',
  '1,230,457',
  '+80',
  '2,241',
  '5',
  '67,418',
  '1,087',
  '7,342,086',
  '395,075',
  '18,584,039 ',
  'North America',
  '',
  '159203',
  '11',
  '',
  '121',
  ''],
 ['',
  '63',
  'Lebanon',
  '1,237,556',
  '',
  '10,914                                ',
  '',
  '1,087,587',
  '',
  '139,055',
  '74',
  '185,128',
  '1,633',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56131',
  '',
  '',
  '20,802',
  ''],
 ['',
  '64',
  'Costa Rica',
  '1,232,576',
  '',
  '9,374                                ',
  '',
  '860,711',
  '',
  '362,491',
  '52',
  '237,841',
  '1,809',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45531',
  '',
  '',
  '69,947',
  ''],
 ['',
  '65',
  'Bolivia',
  '1,199,346',
  '+100',
  '22,384                                ',
  '',
  '1,168,509',
  '+43',
  '8,453',
  '220',
  '100,007',
  '1,866',
  '2,710,261',
  '225,993',
  '11,992,656 ',
  'South America',
  '',
  '105364',
  '8',
  '',
  '705',
  ''],
 ['',
  '66',
  'Tunisia',
  '1,153,323',
  '',
  '29,420                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '44',
  '95,738',
  '2,442',
  '5,012,932',
  '416,126',
  '12,046,656 ',
  'Africa',
  '',
  '104092',
  '',
  '',
  '1,154',
  ''],
 ['',
  '67',
  'Cuba',
  '1,114,241',
  '+38',
  '8,530                                ',
  '',
  '1,105,534',
  '+35',
  '177',
  '2',
  '98,556',
  '754',
  '14,345,279',
  '1,268,859',
  '11,305,652 ',
  'North America',
  '',
  '101,3251',
  '3',
  '',
  '16',
  ''],
 ['',
  '68',
  'UAE',
  '1,067,030',
  '',
  '2,349                                ',
  '',
  '1,054,525',
  '',
  '10,156',
  '',
  '105,837',
  '233',
  '200,732,262',
  '19,910,389',
  '10,081,785 ',
  'Asia',
  '',
  '94,2920',
  '',
  '',
  '1,007',
  ''],
 ['',
  '69',
  'Ecuador',
  '1,062,275',
  '',
  '36,019                                ',
  '',
  '1,025,081',
  '',
  '1,175',
  '759',
  '58,646',
  '1,989',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America',
  '',
  '175036',
  '',
  '',
  '65',
  ''],
 ['',
  '70',
  'Panama',
  '1,040,230',
  '',
  '8,624                                ',
  '',
  '1,030,855',
  '',
  '751',
  '16',
  '233,919',
  '1,939',
  '7,697,189',
  '1,730,886',
  '4,446,964 ',
  'North America',
  '',
  '45161',
  '',
  '',
  '169',
  ''],
 ['',
  '71',
  'Uruguay',
  '1,038,774',
  '',
  '7,634                                ',
  '',
  '1,030,944',
  '',
  '196',
  '18',
  '297,131',
  '2,184',
  '6,114,822',
  '1,749,083',
  '3,496,016 ',
  'South America',
  '',
  '34581',
  '',
  '',
  '56',
  ''],
 ['',
  '72',
  'Mongolia',
  '1,008,655',
  '',
  '2,179                                ',
  '',
  '1,006,086',
  '+227',
  '390',
  '192',
  '298,588',
  '645',
  '4,030,048',
  '1,193,000',
  '3,378,078 ',
  'Asia',
  '',
  '31,5501',
  '',
  '',
  '115',
  ''],
 ['',

In [14]:
# Find file location
pwd

'C:\\Users\\prajw\\Python_class_630am'

In [18]:
total_cases = df['TotalCases']
total_cases = list(map(lambda x:int(x.replace(',' , '')),list(df['TotalCases'])))
total_cases

AttributeError: 'float' object has no attribute 'replace'

In [20]:
!pip install plotly==5.14.1

Collecting plotly==5.14.1
  Downloading plotly-5.14.1-py2.py3-none-any.whl (15.3 MB)
     ---------------------------------------- 15.3/15.3 MB 2.7 MB/s eta 0:00:00
Requirement already satisfied: tenacity>=6.2.0 in c:\users\prajw\anaconda3\lib\site-packages (from plotly==5.14.1) (8.0.1)
Requirement already satisfied: packaging in c:\users\prajw\anaconda3\lib\site-packages (from plotly==5.14.1) (22.0)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.9.0
    Uninstalling plotly-5.9.0:
      Successfully uninstalled plotly-5.9.0
Successfully installed plotly-5.14.1